export type GpuRecipe = {
  id: string;
  title: string;
  lesson: string;
  repo: string;
  hardware: string;
  notes: string;
};

export const gpuRecipes: readonly GpuRecipe[] = [
  {
    id: "avalanche-naive",
    title: "Avalanche SplitMNIST Naive / EWC",
    lesson: "01, 05",
    repo: "https://github.com/ContinualAI/avalanche",
    hardware: "单卡 8GB 够 SplitMNIST",
    notes: "官方 From Zero to Hero。分数不要写进课内 CPU 的 result.json。",
  },
  {
    id: "mammoth-derpp",
    title: "Mammoth DER++",
    lesson: "06",
    repo: "https://github.com/aimagelab/mammoth",
    hardware: "单卡 12GB 做 CIFAR",
    notes: "复现 #1。python main.py --model derpp --dataset seq-cifar10 --buffer_size 500",
  },
  {
    id: "mammoth-gdumb",
    title: "Mammoth GDumb vs A-GEM",
    lesson: "08",
    repo: "https://github.com/aimagelab/mammoth",
    hardware: "与 DER++ 相同",
    notes: "复现 #2。同一 buffer_size 才能比。",
  },
  {
    id: "olora",
    title: "O-LoRA 顺序指令",
    lesson: "10, 11",
    repo: "https://github.com/cmnfriend/O-LoRA",
    hardware: "T5-large 单卡 24GB 更稳",
    notes: "论文 arXiv:2310.14152。不要用 2305.18870。",
  },
  {
    id: "treelora",
    title: "TreeLoRA",
    lesson: "11",
    repo: "https://github.com/ZinYY/TreeLoRA",
    hardware: "常见单卡 24GB",
    notes: "arXiv:2506.10355。对照 O-LoRA，不要混成同一个方法。",
  },
  {
    id: "ttt-pytorch",
    title: "TTT-Linear 官方 PyTorch",
    lesson: "17",
    repo: "https://github.com/test-time-training/ttt-lm-pytorch",
    hardware: "短序列 CPU 也能看定义；正经 LM 要 GPU",
    notes: "仓库声明不适合大规模训练。",
  },
  {
    id: "razor-mnist",
    title: "RL's Razor MNIST",
    lesson: "20",
    repo: "https://github.com/SakanaAI/rl-razor-mnist",
    hardware: "单卡 8GB 或 CPU 较慢",
    notes: "复现 #5。对照 grpo 与 sft1 的旧任务保持。",
  },
  {
    id: "seal",
    title: "SEAL 自编辑",
    lesson: "20, 23",
    repo: "https://github.com/Continual-Intelligence/SEAL",
    hardware: "官方写 2×A100/H100",
    notes: "内环是 LoRA SFT，写进权重。缺卡就读 general-knowledge/ 与 few-shot/。",
  },
  {
    id: "easyedit",
    title: "EasyEdit / ROME",
    lesson: "14",
    repo: "https://github.com/zjunlp/EasyEdit",
    hardware: "GPT-2 级单卡 8–12GB",
    notes: "课内 CPU 是符号 rank-1。",
  },
  {
    id: "mergekit",
    title: "mergekit",
    lesson: "12",
    repo: "https://github.com/arcee-ai/mergekit",
    hardware: "7B 要能装下两份权重",
    notes: "离线合并，不是每天的在岗学习。",
  },
  {
    id: "smollm-lora",
    title: "SmolLM2-135M 短适配",
    lesson: "04, 09, 10",
    repo: "https://huggingface.co/HuggingFaceTB/SmolLM2-135M",
    hardware: "单卡 8–12GB",
    notes: "把日记巩固成真微调时用。配方见 GPU.md。",
  },
  {
    id: "plasticity",
    title: "Loss of Plasticity",
    lesson: "15",
    repo: "https://github.com/shibhansh/loss-of-plasticity",
    hardware: "MNIST 变体单卡可做",
    notes: "复现 #4。后期学习变慢。",
  },
  {
    id: "letta-mem0",
    title: "Letta / Mem0（对照）",
    lesson: "13, 21, 24",
    repo: "https://github.com/mem0ai/mem0",
    hardware: "API 或本地 OpenAI 兼容端点",
    notes: "脚手架。卸掉存储就不会。巩固进权重才是终点。",
  },
  {
    id: "hipporag",
    title: "HippoRAG 2",
    lesson: "13",
    repo: "https://github.com/OSU-NLP-Group/HippoRAG",
    hardware: "OpenAI API 可跑 demo；本地 Llama 要 vLLM",
    notes: "非参数持续学习。新知识进图，不进权重。卸掉 save_dir 就不会。",
  },
  {
    id: "voyager",
    title: "Voyager 技能库（对照）",
    lesson: "21",
    repo: "https://github.com/MineDojo/Voyager",
    hardware: "Minecraft + GPT-4 API",
    notes: "技能卡在文件里，权重没动。对应 extra skill。",
  },
  {
    id: "awm",
    title: "Agent Workflow Memory",
    lesson: "21",
    repo: "https://github.com/zorazrw/agent-workflow-memory",
    hardware: "WebArena / Mind2Web，主要吃 API",
    notes: "工作流写在记忆里。对应 extra skill。",
  },
  {
    id: "trace",
    title: "TRACE 顺序指令",
    lesson: "10",
    repo: "https://github.com/BeyonderXX/TRACE",
    hardware: "1B 级可单卡 24GB 试 naive",
    notes: "arXiv:2310.06762。bash scripts/train_seq_naive.sh",
  },
  {
    id: "memoryllm",
    title: "MemoryLLM 潜空间记忆池",
    lesson: "13, 16",
    repo: "https://github.com/wangyu-ustc/MemoryLLM",
    hardware: "8B 要 80GB 或量化",
    notes: "inject_memory 写进模型内的记忆池，不是 Mem0，也不是骨干 MLP。",
  },
  {
    id: "mammoth-l2p",
    title: "Mammoth L2P / DualPrompt",
    lesson: "07",
    repo: "https://github.com/aimagelab/mammoth",
    hardware: "ViT-CIFAR，timm==0.9.8",
    notes: "另长一块 prompt，旧骨干冻结。",
  },
  {
    id: "avalanche-ewc",
    title: "Avalanche EWC",
    lesson: "05",
    repo: "https://github.com/ContinualAI/avalanche",
    hardware: "SplitMNIST 单卡 8GB 或 CPU",
    notes: "对照 extra ewcmem。",
  },
  {
    id: "avalanche-lwf",
    title: "Avalanche LwF",
    lesson: "05, 06",
    repo: "https://github.com/ContinualAI/avalanche",
    hardware: "SplitMNIST 单卡 8GB 或 CPU",
    notes: "无缓冲。对照 extra gendream。",
  },
  {
    id: "vandeven-lwf",
    title: "van de Ven LwF",
    lesson: "01, 06",
    repo: "https://github.com/GMvandeVen/continual-learning",
    hardware: "SplitMNIST 桌面约 6 分钟",
    notes: "./main.py --experiment=splitMNIST --scenario=task --lwf",
  },
  {
    id: "vandeven-dgr",
    title: "van de Ven 生成回放",
    lesson: "06, 16",
    repo: "https://github.com/GMvandeVen/continual-learning",
    hardware: "SplitMNIST 单卡 8GB",
    notes: "--replay=generative。做梦，不留 exemplar。对照 extra gendream。",
  },
  {
    id: "vandeven-er",
    title: "van de Ven 经验回放（对照）",
    lesson: "06, 16",
    repo: "https://github.com/GMvandeVen/continual-learning",
    hardware: "与 LwF 相同",
    notes: "--replay=buffer 仍是外挂。对照 extra buffer。",
  },
  {
    id: "mammoth-lwf",
    title: "Mammoth LwF",
    lesson: "06",
    repo: "https://github.com/aimagelab/mammoth",
    hardware: "seq-cifar10 单卡 12GB",
    notes: "python main.py --model lwf --dataset seq-cifar10",
  },
  {
    id: "mammoth-icarl",
    title: "Mammoth iCaRL",
    lesson: "06, 08",
    repo: "https://github.com/aimagelab/mammoth",
    hardware: "与 DER++ 相同",
    notes: "exemplar 卸掉就不能护旧类。对照 extra buffer。",
  },
  {
    id: "pycil",
    title: "PyCIL",
    lesson: "01, 06, 08",
    repo: "https://github.com/G-U-N/PyCIL",
    hardware: "CIFAR-100 单卡 8–12GB",
    notes: "python main.py --config=./exps/lwf.json 或 icarl.json",
  },
  {
    id: "inflora",
    title: "InfLoRA",
    lesson: "11, 16",
    repo: "https://github.com/liangyanshuo/InfLoRA",
    hardware: "1×A6000 或 4×2080Ti；CIFAR-100 可先试",
    notes: "arXiv:2404.00228。对照 extra ortho。",
  },
  {
    id: "easyedit-wise",
    title: "EasyEdit WISE",
    lesson: "14, 16",
    repo: "https://github.com/zjunlp/EasyEdit",
    hardware: "7–8B 至少 24–48GB",
    notes: "终身编辑 sequential_edit=True。对照 extra stale / tombstone。",
  },
  {
    id: "langmem",
    title: "LangMem（对照）",
    lesson: "13, 21",
    repo: "https://github.com/langchain-ai/langmem",
    hardware: "API，不需要训练卡",
    notes: "写进 Store。卸掉 Store 就不会。",
  },
  {
    id: "graphiti",
    title: "Graphiti / Zep（对照）",
    lesson: "13",
    repo: "https://github.com/getzep/graphiti",
    hardware: "Neo4j + API",
    notes: "新知识进图。卸掉图就不会。",
  },
  {
    id: "unsloth-lora",
    title: "Unsloth 短适配",
    lesson: "09, 16, 24",
    repo: "https://github.com/unslothai/unsloth",
    hardware: "135M–1B 单卡 8–12GB 常见",
    notes: "把筛选过的日记做成 SFT。对照 extra distill。",
  },
  {
    id: "llama-factory",
    title: "LLaMA-Factory",
    lesson: "09, 10, 16",
    repo: "https://github.com/hiyouga/LLaMA-Factory",
    hardware: "7–8B LoRA 常见单卡 24GB",
    notes: "夜间巩固的工程入口。数据换成筛选过的日记。",
  },
  {
    id: "pilot",
    title: "PILOT",
    lesson: "07, 11",
    repo: "https://github.com/sun-hailong/LAMDA-PILOT",
    hardware: "ViT 单卡 12GB 起",
    notes: "L2P / DualPrompt / CODA-Prompt。骨干冻结。",
  },
];
