export interface LessonPractice {
  lessonId: string;
  purpose: string;
  proves: readonly string[];
  doesNotProve: string;
  sourceFile: string;
}

export const practiceRepositoryUrl =
  "content/omni/experiments";

const practices = [
  {
    lessonId: "01",
    purpose: "固定随机种子，比较两次 token trace，并验证不同种子确实会改变结果。",
    proves: ["相同输入和种子得到相同 trace", "结果文件记录了可复核的摘要"],
    doesNotProve: "它不训练 MiniMind-O，也不能代替 128 样本过拟合和 GPU 复现。",
    sourceFile: "lesson_01.py",
  },
  {
    lessonId: "02",
    purpose: "让两种 connector 在同一输入上压缩 token，并核对输出预算与 padding 处理。",
    proves: ["连接器遵守统一输入输出契约", "不同压缩预算被明确记录"],
    doesNotProve: "它不说明哪种 connector 在真实图像或语音任务上质量更高。",
    sourceFile: "lesson_02.py",
  },
  {
    lessonId: "03",
    purpose: "计算 codec 名义码率与有效熵，并检查流式分块和离线重建的一致性。",
    proves: ["码率公式和单位可以手算复核", "流式状态不会跨会话污染"],
    doesNotProve: "它不评估真实 codec 的音质、说话人保持或下游 WER。",
    sourceFile: "lesson_03.py",
  },
  {
    lessonId: "04",
    purpose: "构造多码本 diagonal delay schedule，再执行逆变换恢复原始帧。",
    proves: ["schedule 与 next-token shift 被分开", "delay 变换可以无损还原"],
    doesNotProve: "它不证明某种 Talker 拓扑能生成更自然的语音。",
    sourceFile: "lesson_04.py",
  },
  {
    lessonId: "05",
    purpose: "用相同前缀、不同未来后缀验证因果 Listener 不会提前读取未来。",
    proves: ["共享前缀的已发布状态完全相同", "分块时间戳满足 available_at 约束"],
    doesNotProve: "它不包含真实 ASR encoder、蒸馏训练或网络抖动测试。",
    sourceFile: "lesson_05.py",
  },
  {
    lessonId: "06",
    purpose: "在固定事件时间线上运行话轮策略，检查阈值、迟滞和 cooldown。",
    proves: ["策略输出可重复", "WAIT、接话和打断条件能被逐项检查"],
    doesNotProve: "它不代表模型在真实双声道对话上的事件检测准确率。",
    sourceFile: "lesson_06.py",
  },
  {
    lessonId: "07",
    purpose: "重放一组输入和播放事件，验证 CONTINUE、PAUSE、REPLAN 的状态转换。",
    proves: ["输出期间仍持续消费输入", "已播放音频与待播放音频被分开处理"],
    doesNotProve: "它不运行真实 Thinker、Talker、AEC 或长时间稳定性测试。",
    sourceFile: "lesson_07.py",
  },
  {
    lessonId: "08",
    purpose: "为宽图和多图规划 tile，并生成带 image id 的二维位置坐标。",
    proves: ["tile 数不超过预算", "相同局部坐标仍能区分不同图片"],
    doesNotProve: "它不证明 M-RoPE 会提升真实视觉问答准确率。",
    sourceFile: "lesson_08.py",
  },
  {
    lessonId: "09",
    purpose: "构造视频帧和音频时间戳，检查下采样后的真实时间与 AV 对齐误差。",
    proves: ["时间戳随下采样正确传播", "音频与视频使用同一时间基准"],
    doesNotProve: "它不解码真实视频，也不比较 Conv1D、Conv3D 的模型质量。",
    sourceFile: "lesson_09.py",
  },
  {
    lessonId: "10",
    purpose: "在同一 token 预算下比较几种压缩结果，并计算非支配 Pareto 前沿。",
    proves: ["压缩后 token 数符合预算", "Pareto 判断可以逐点复核"],
    doesNotProve: "它不包含真实视觉特征、CUDA 延迟或任务准确率。",
    sourceFile: "lesson_10.py",
  },
  {
    lessonId: "11",
    purpose: "执行 dropless top-k expert routing，核对每个 token 的 dispatch 次数和负载统计。",
    proves: ["每个 token 恰好路由到 top-k 个专家", "没有 token 在 dispatch 中被静默丢弃"],
    doesNotProve: "它不衡量 grouped GEMM、all-to-all 或 MoE 训练收益。",
    sourceFile: "lesson_11.py",
  },
  {
    lessonId: "12",
    purpose: "在 packed sequence 上运行递归状态更新，并验证样本边界会重置状态。",
    proves: ["边界后的状态不依赖上一个样本", "不重置状态的负对照会产生不同结果"],
    doesNotProve: "它不调用官方 Mamba-2 CUDA kernel，也不比较长序列吞吐。",
    sourceFile: "lesson_12.py",
  },
  {
    lessonId: "13",
    purpose: "把 8 个 rank 映射到并行 mesh，核对坐标唯一性与 group 正交性。",
    proves: ["mesh 维度乘积等于 world size", "每个 rank 恰好拥有一个坐标"],
    doesNotProve: "它只验证分布式语义，不验证 8 卡 NCCL 性能和数值一致性。",
    sourceFile: "lesson_13.py",
  },
  {
    lessonId: "14",
    purpose: "构造渐进式长度课程，计算 RoPE 角度并检查 token 计数连续性。",
    proves: ["上下文长度按阶段单调增加", "课程权重与累计 token 可复核"],
    doesNotProve: "它不证明模型已经获得 128K 长上下文能力。",
    sourceFile: "lesson_14.py",
  },
  {
    lessonId: "15",
    purpose: "比较按样本数与按 token 数统计的模态曝光，并核对 8 路 codec shift 与 mask。",
    proves: ["样本占比和 token 占比被分开计算", "8 路 codec target 的 shift 与有效位置可逐项检查"],
    doesNotProve: "它不训练 Joint SFT，也不能说明遗忘是否得到控制。",
    sourceFile: "lesson_15.py",
  },
  {
    lessonId: "16",
    purpose: "用给定的 toy sequence log-prob 手算 DPO/mDPO margin 与 loss，并交换 chosen/rejected 做负对照。",
    proves: ["偏好方向翻转时 loss 按公式变化", "每个给定的 toy log-prob 都进入预期 margin"],
    doesNotProve: "它不包含真实偏好数据、图像 crop 或多模态训练。",
    sourceFile: "lesson_16.py",
  },
  {
    lessonId: "17",
    purpose: "对一组 rollout reward 计算 group-relative advantage，并区分错误答案与 verifier 系统故障。",
    proves: ["组内 advantage 均值接近零", "错误答案保留为低分样本，verifier 系统故障会被丢弃"],
    doesNotProve: "它不执行 optimizer step，也不运行真实 policy rollout、分布式更新或 held-out RLVR 评测。",
    sourceFile: "lesson_17.py",
  },
  {
    lessonId: "18",
    purpose: "计算 LoRA 参数量，执行 adapter merge 等价检查，并核对 256 个图像位置的长度账本。",
    proves: ["LoRA shape 与参数公式一致", "merge 前后结果在数值容差内一致", "按 256 个图像位置记账后的序列长度正确"],
    doesNotProve: "它不加载 Nemotron 30B，也没有验证真实 processor、collator、CORD 微调或恢复训练。",
    sourceFile: "lesson_18.py",
  },
  {
    lessonId: "19",
    purpose: "运行 UTF-8 token 对齐 toy，并在一条手工事件时间线上重放 pause、resume 与 replan。",
    proves: ["两种 tokenizer 的共享字节前缀可以单调对齐", "单状态机 fixture 的事件顺序与动作可复核"],
    doesNotProve: "它不验证四条真实时钟、branch checkpoint、播放器停播、Nemotron hidden state 或真实语音链路。",
    sourceFile: "lesson_19.py",
  },
  {
    lessonId: "20",
    purpose: "运行 1D flow-matching toy，并检查 noisy-latent patch 数与两类 attention block mask。",
    proves: ["flow target 与反向积分方向可手算复核", "256 个 latent patch 的记账和 route-specific mask 满足 toy contract"],
    doesNotProve: "它不验证联合 loss、三臂真实实现、共享 checkpoint，也不训练 VAE、flow head 或统一理解生成模型。",
    sourceFile: "lesson_20.py",
  },
  {
    lessonId: "21",
    purpose: "在固定 4×4 相似度矩阵上核对 InfoNCE、sigmoid 损失、温度缩放和打乱对照",
    proves: [
      "打乱配对后 InfoNCE 与 sigmoid 损失都不低于对齐矩阵",
      "温度从 0.01 升到 0.2 时正对 softmax 峰值下降",
      "InfoNCE 对全局平移不变，sigmoid 损失会变",
    ],
    doesNotProve: "不证明真实 CLIP/SigLIP 的 ImageNet 成功率，也不代替大规模训练",
    sourceFile: "lesson_21.py",
  },
  {
    lessonId: "22",
    purpose: "按模块统计可训练参数，并验证只训投影时 ViT 与 LLM 梯度为零",
    proves: [
      "阶段 1 可训练参数等于投影矩阵元素数",
      "mask 之后 ViT 与 LLM 的反传梯度精确为零",
      "LoRA 参数量等于 r(d_in+d_out)，且基座 LLM 梯度仍被挡住",
    ],
    doesNotProve: "不证明某个真实 VLM 的 VQA 分数或遗忘幅度",
    sourceFile: "lesson_22.py",
  },
  {
    lessonId: "23",
    purpose: "在固定框与 8×8 注意力夹具上计算 IoU 命中、注意力质量分数和 POPE 幻觉率。",
    proves: [
      "IoU 与注意力命中的公式可独立复核",
      "存在「VQA 答案对、对被问物体命中失败」的夹具",
      "幻觉率只在物体不存在的负例上计算，且不等于 Yes 比例",
    ],
    doesNotProve: "不证明任何真实 VLM 的幻觉率或 RefCOCO 准确率。",
    sourceFile: "lesson_23.py",
  },
  {
    lessonId: "24",
    purpose: "核对 7 维均匀分箱边界、词表偏移，以及语言头与动作 token 的梯度隔离",
    proves: [
      "低端点映射到 bin 0、高端点映射到 bin B-1，区间左闭右开",
      "动作 token 占据 [V, V+7B) 且维与维不重叠",
      "只训独立语言头时动作 token 行梯度为 0",
      "联合 softmax 的语言交叉熵仍会给动作行非零梯度",
    ],
    doesNotProve: "不证明真机抓取成功率，也不证明 256 bin 或 55B 骨干在本机可训练",
    sourceFile: "lesson_24.py",
  },
  {
    lessonId: "25",
    purpose: "在固定 7 维示教上核对分箱误差上界、B=2 高频塌缩、H/f 线性开环，以及 DCT 保留系数的 token 数。",
    proves: [
      "均匀分箱最大误差不超过箱宽一半",
      "开环时长随分块长度线性增加",
      "连续 L1 重建误差为 0 且并行串行深度为 1",
    ],
    doesNotProve: "不证明任何真实机械臂成功率，也不复现 FAST 或 OpenVLA 的训练。",
    sourceFile: "lesson_25.py",
  },
  {
    lessonId: "26",
    purpose: "在四域计数 (10000, 1000, 200, 100) 上核对温度混合、每域上限，以及指令打乱与机体 ID 泄漏夹具。",
    proves: [
      "α=1 时最大域占比超过 75%",
      "每域条数上限会抬高最小域采样频率",
      "指令打乱会打掉无泄漏时的语言政策",
      "机体 ID 泄漏政策在打乱指令后仍保持高准确率，打乱机体标签后下降",
    ],
    doesNotProve: "不证明任何真实机械臂成功率，也不复现 OXE、Octo 或 OpenVLA 的预训练。",
    sourceFile: "lesson_26.py",
  },
  {
    lessonId: "27",
    purpose: "实现 bin 化动作的 teacher-forced CE 与并行 L1，核对张量形状和 loss 位置 mask。",
    proves: [
      "CE 只在 7 个动作位置计 loss，prompt 与 padding 为 IGNORE",
      "并行 L1 预测形状为 [B, H, 7]，padded 时间步被 mask 掉",
      "同一 bin 边界上 CE 类别跳变，L1 仍按连续差计罚",
    ],
    doesNotProve: "它不训练 OpenVLA，也不报告 LIBERO 或真机成功率。",
    sourceFile: "lesson_27.py",
  },
  {
    lessonId: "28",
    purpose: "在二维动作块上手算一个时间步的目标速度，核对 Euler 积分把噪声推向干净动作。",
    proves: [
      "直线路径的数值导数等于噪声减干净动作",
      "正确速度让距离下降，反号速度让距离上升",
      "第 20 课约定与 π0 约定在对应步长下走到同一下一状态",
    ],
    doesNotProve: "它不训练动作专家，也不报告真机或仿真抓取成功率。",
    sourceFile: "lesson_28.py",
  },
  {
    lessonId: "29",
    purpose: "用两个离散时间循环核对：控制环每步消费当前子目标，规划环不是每步都跑。",
    proves: [
      "ΔT2 = k ΔT1 且规划时刻是 k 的倍数",
      "System 2 暂停超过过期步数后任务失败",
      "错误子目标改变末端轨迹",
    ],
    doesNotProve: "不证明 GR00T 或 π0.5 的真机成功率，也不证明 VLM 表征可解释。",
    sourceFile: "lesson_29.py",
  },
  {
    lessonId: "30",
    purpose: "用确定性事件时间线证明 freshness 不等式、过期丢弃和 REPLAN 后不再执行旧剩余步。",
    proves: [
      "d < H/f 时 chunk 可执行，d >= H/f 时过期块被丢弃且零步执行。",
      "REPLAN 将旧 branch 标为 superseded，旧剩余步不出现在执行表。",
      "PAUSE 期间不推进动作，CONTINUE 仍走同一 branch。",
    ],
    doesNotProve: "不证明任何真实机械臂、LIBERO 或 ALOHA 任务的成功率。",
    sourceFile: "lesson_30.py",
  },
  {
    lessonId: "31",
    purpose: "对给定成功/失败序列计算点估计、正态近似区间和 Wilson 区间，并检查 N 太小时区间覆盖 0.5。",
    proves: [
      "N=25、k=20 的 Wilson 区间与手算 [0.609, 0.911] 一致",
      "N=5、k=4 的 Wilson 区间覆盖 0.5",
      "四套件宏平均会掩盖 Long 的掉点",
      "接触成功与放置/保持成功可以在同一轨迹上不一致",
    ],
    doesNotProve: "不证明任何真实 VLA 的仿真或真机成功率，也不能把夹具数字标成 SOTA。",
    sourceFile: "lesson_31.py",
  },
  {
    lessonId: "32",
    purpose: "用手算核对 SoM 分类与连续坐标回归的归一化、256 档分箱和编号范围。",
    proves: [
      "点击和末端 xy 可以写进同一张 [0,1]^2 表。",
      "低分辨率格子中心误差大于正确编号的分类损失。",
      "共享比例头能同时降低 UI 与桌面样本的 MSE。",
    ],
    doesNotProve: "不证明真机抓取成功率，也不证明 OSWorld / LIBERO 上的代理能力。",
    sourceFile: "lesson_32.py",
  },
  {
    lessonId: "33",
    purpose: "在固定 8 步接触/分离序列上核对像素 L2 与表征回归，以及遮挡后接触探针是否还分得开。",
    proves: [
      "遮挡未来后像素 L2 上升，表征回归保持同阶或下降。",
      "像素接触差塌掉，表征 overlap 仍分开接触与分离。",
      "常数编码器触发 VICReg 方差项；stop-gradient 挡住目标支路。",
    ],
    doesNotProve: "不证明 V-JEPA 2-AC 的真机成功率，也不证明 Cosmos 式视频生成已经学会物理。",
    sourceFile: "lesson_33.py",
  },
  {
    lessonId: "34",
    purpose: "用手算核对跨帧物体 ID 计数器和自由下落的重力符号探针。",
    proves: [
      "干净滚动不丢物体 ID，Δv_y 与真重力同号。",
      "人为丢掉 ID 后计数器大于 0。",
      "把 g 取反后符号探针报警。",
      "用翻转重力选出的动作，在真实世界里更偏离捕捉目标。",
    ],
    doesNotProve: "不证明 Cosmos、Genie 或 V-JEPA 2 的真机成功率，也不能把夹具数字标成物理仿真器已可靠。",
    sourceFile: "lesson_34.py",
  },
  {
    lessonId: "35",
    purpose: "用手算核对 (u,v,z) 反投影、无深度取均值导致接触失败，以及极坐标与体素索引。",
    proves: [
      "同一像素用均值深度反投影时 RGB 误差为 0，接触带判定为假。",
      "换真实深度后 RGB 命中与三维接触同时为真。",
      "相机系点可写成极坐标并往返；体素索引能分开两种深度。",
    ],
    doesNotProve: "不证明 SimplerEnv / LIBERO / 真机抓取成功率，也不证明 ZoeDepth 估计在本机可运行。",
    sourceFile: "lesson_35.py",
  },
  {
    lessonId: "36",
    purpose: "核对手臂与底盘词表偏移不重叠，以及丢地图后路点策略输出非法索引、速度策略仍落在底盘词表内。",
    proves: [
      "手臂切片和底盘切片在整数 id 上不相交",
      "(v,ω) 与手臂 x / yaw 的箱宽不同，共用手臂箱边会把快速底盘速度裁进最后一格",
      "地图节点数 N=0 时路点索引非法",
      "丢地图后速度 token 仍落在底盘词表，并在教学单车上撞墙或转圈",
    ],
    doesNotProve: "不证明真机导航或抓取成功率，也不复现 RT-1、NaVILA 或 Mobility VLA 的训练。",
    sourceFile: "lesson_36.py",
  },
  {
    lessonId: "37",
    purpose: "在固定预算下对照 d=7 与 d=24 的分块长度、每维量化宽度，以及手指高频重建误差。",
    proves: [
      "token 预算守恒：7×24=24×7=168",
      "比特预算下 d=24 的箱宽大于 d=7",
      "手指高频重建误差随维数升高而上升，且升幅大于躯干",
    ],
    doesNotProve: "不证明灵巧手或人形真机成功率，也不复现 GR-3、Helix 或 Gemini Robotics 的训练。",
    sourceFile: "lesson_37.py",
  },
  {
    lessonId: "38",
    purpose: "用手算核对失败组上稀疏优势全零、接触 dense 仍可排序并产生非零更新。",
    proves: [
      "全失败稀疏组方差为零，标量权重不变。",
      "dense 在四条失败轨迹上排序为擦边、压溃、悬停、空抓。",
      "混入一条成功后，稀疏才能分出正负优势。",
    ],
    doesNotProve: "不证明真机抓取成功率，也不证明 LIBERO / 真机 RFT 数字。",
    sourceFile: "lesson_38.py",
  },
  {
    lessonId: "39",
    purpose: "用手算和 CPU 回放核对：第二步失败后，栈不重做已提交步，窗口回放会。",
    proves: [
      "同一栈操作序列可回放",
      "失败不把已提交子目标重新执行",
      "窗口回放会第二次执行第一步",
      "k 与 T 取值不同，加大 T 不取消重放",
    ],
    doesNotProve: "不证明 CALVIN、HULC 或真机长程成功率，也不能把夹具数字标成 0.08% 或 38.3%。",
    sourceFile: "lesson_39.py",
  },
  {
    lessonId: "40",
    purpose: "用确定性 chunk 回放证明超限后剩余步为 0，SAFE_HOLD 不推进末端，物体不能退回超限前。",
    proves: [
      "||F_i|| > F_max 时丢掉 i+1 以后的步，剩余步计数为 0。",
      "SAFE_HOLD 与人类接管期间末端坐标不变。",
      "杯子位移在超限步已经发生，回放不得把它写回超限前。",
    ],
    doesNotProve: "不证明任何真实机械臂、LIBERO 或 ISO 力限制认证的成功率。",
    sourceFile: "lesson_40.py",
  },
  {
    lessonId: "41",
    purpose: "用手算核对理解 mask 看全图、生成 mask 挡住未来像素，以及码本索引与统一词表偏移。",
    proves: [
      "理解路径的图像 query 能看见全部图像 key，包括光栅顺序上的未来格。",
      "生成路径的图像 query 不能看见未来像素 token，提示 token 也不能看图像。",
      "码本编号落在 [0, K-1]，统一 id 等于文本词表偏移加码本编号。",
    ],
    doesNotProve: "不训练 Chameleon / Emu3 / Show-o，也不报告 FID、GenEval 或 VQA。",
    sourceFile: "lesson_41.py",
  },
  {
    lessonId: "42",
    purpose: "用手算核对字-图-字日程的提交序列与注意力 mask，确认内步不进入文本 KV。",
    proves: [
      "工作区策略下图像内步不在已提交 KV 里，文本查询对内步的可见性为 0。",
      "把内步写入 KV 后，后续文本会读到这些位置。",
      "调换日程后提交顺序和图像提交下标都改变。",
      "Transfusion 式图内双向 mask 与 Janus 式全因果 mask 不是同一张表。",
    ],
    doesNotProve: "不证明真实 FID / GenEval，也不证明端侧交错生成的时延。",
    sourceFile: "lesson_42.py",
  },
  {
    lessonId: "43",
    purpose: "在固定 20 位置序列上核对 ASR 与指令跟随两类 mask 的有效 token 集合。",
    proves: [
      "两类有效集合不相等、不相交。",
      "音频帧和提示不进入任一张 mask。",
      "复读模型的 ASR 交叉熵低于指令交叉熵，污染集合是真超集。",
    ],
    doesNotProve: "不证明 AIR-Bench、VoiceBench 或口述 MMLU 的真实分数。",
    sourceFile: "lesson_43.py",
  },
  {
    lessonId: "44",
    purpose: "在固定发票夹具上计算内容命中、框 IoU 和合取后的版面命中，并核对阅读顺序与跨页查找。",
    proves: [
      "内容对且框在表头时版面命中为假",
      "字段级 F1 在单字符缺失时下降，TED 在结构被拍平时下降",
      "栅格顺序与版面阅读顺序不相等；只看见第 1 页时跨页键值查找失败",
    ],
    doesNotProve: "不证明任何真实文档模型在 CORD、FUNSD 或 DocVQA 上的成功率。",
    sourceFile: "lesson_44.py",
  },
  {
    lessonId: "45",
    purpose: "在 60 段一分钟索引上核对三层余弦排序、Recall@5 和阅读预算。",
    proves: [
      "目标段只在中间层进入 Recall@5。",
      "字幕层被有声但视觉错误的阀门描述带走。",
      "像素层查询投影错误时召回为 0，整段扫描超过阅读预算。",
      "先中间层召回再对少数片段精读，目标仍在集合内且预算低于整段像素扫描。",
    ],
    doesNotProve: "不证明 Video-MME、MLVU 或真机长操作记录上的任务成功率。",
    sourceFile: "lesson_45.py",
  },
  {
    lessonId: "46",
    purpose: "用手算两条变长视觉请求的 padding mask，确认无效位置不进入有效 token 计数和注意力分母。",
    proves: [
      "有效 token 数等于各请求真实视觉加文本长度之和，不等于 padded 形状。",
      "错误 mask 会把无效 key 的注意力质量变成正数。",
      "把纯文本和动作专家垫进同一静态图会继续降低有效比，并让动作页与 AR 页重叠。",
    ],
    doesNotProve: "不测量真实 GPU 吞吐，也不复现 vLLM-Omni 的 91.4% JCT 降幅。",
    sourceFile: "lesson_46.py",
  },
  {
    lessonId: "47",
    purpose: "给六条公开数字打互斥标签，拒绝跨类减法和把 LIBERO 平均标成真机能力。",
    proves: [
      "六类标签两两不相交，每条记录恰好一类",
      "LIBERO 宏平均不能标成真机能力",
      "SIMPLER 的 Pearson r 不能当成功率",
      "只有同类、同单位时才允许做差，Wilson 区间沿用第 31 课 N=25、k=20 的手算",
    ],
    doesNotProve: "不证明任何真实模型在六类基准上的能力，也不能把夹具数字标成 SOTA。",
    sourceFile: "lesson_47.py",
  },
  {
    lessonId: "48",
    purpose: "用一张状态表、两列时间戳证明：PAUSE 与 REPLAN 分事件，REPLAN 后旧 PCM 与旧剩余步都不执行，且不撤回历史。",
    proves: [
      "音频过期用 320 ms 块，动作过期用 H/f，同一延迟可以只让一边过期。",
      "音频 PAUSE 不丢手臂剩余步；力切断不停嘴。",
      "REPLAN 取消未播 PCM 和未执行剩余步，已播 PCM 与接触仍在。",
    ],
    doesNotProve: "不证明任何真机双工机器人、LIBERO 成功率，也不证明复现了 GPT-4o 或 Helix。",
    sourceFile: "lesson_48.py",
  },
  {
    lessonId: "49",
    purpose: "证明理解 CE 与生成帧差的有效位置不相交，并造出理解答对、生成帧杯子消失。",
    proves: [
      "CE mask 与帧差 mask 交为空，非法 OR 会同时盖住答案 token 和未来格子。",
      "历史 5 帧杯子占用为 1，理解 argmax 为“还在”。",
      "遗忘生成占用为 0，且均值填充 L2 可以低于抄上一帧。",
      "Video-MME 准确率不得记成生成分数；相机命中与 Video-MME 不同账。",
    ],
    doesNotProve:
      "不训练 CogVideoX / HunyuanVideo，不报告 VBench 或 Video-MME 真实分数，也不证明 Sora 的内部结构。",
    sourceFile: "lesson_49.py",
  },
  {
    lessonId: "50",
    purpose: "用手算核对 mesh / 高斯 / 辐射场的输出 shape，以及高斯半径不得改 mesh 拓扑、写回 latent 时另两路失败。",
    proves: [
      "三种解码输出的 shape 互不相同，且都由同一份只读 SLAT 算出。",
      "加大高斯半径后 mesh 拓扑哈希不变、辐射场因子不变、高斯尺度变大。",
      "高斯解码器把半径写进 z_i 后，mesh 拓扑与辐射场同时与基线不一致。",
    ],
    doesNotProve: "不训练 TRELLIS，也不报告 Toys4k FID、用户偏好或真机资产可用性。",
    sourceFile: "lesson_50.py",
  },
  {
    lessonId: "51",
    purpose: "在固定计数夹具上拆开推理 token 与答案 token，并证明无视觉引用时过程奖励为 0。",
    proves: [
      "推理与答案的位置集合不相交",
      "引用格为空或只点到干扰格时过程奖励为 0",
      "关掉必须引用后答案仍可对，合取奖励为 0",
    ],
    doesNotProve: "不证明 LLaVA-CoT 或 Vision-R1 的真实基准分数，也不证明长思维链一定忠实。",
    sourceFile: "lesson_51.py",
  },
  {
    lessonId: "52",
    purpose: "在固定发票夹具上核对 OCR 命中、心算进位误差和计算器真值，并用 JSON schema 拒绝缺参数调用。",
    proves: [
      "印刷数字被 OCR 读对时，漏进位的心算是 51.20，计算器是 61.20。",
      "缺 expression 的 calculator 调用不得执行。",
      "缺框的 crop 与越界的 depth 不得执行。",
      "目录外的工具名被拒绝，不得假装已经查过。",
    ],
    doesNotProve: "不证明真实发票、MathVista、V*Bench 或 OSWorld 上的任务成功率。",
    sourceFile: "lesson_52.py",
  },
  {
    lessonId: "53",
    purpose: "用三条记忆记录证明：全留像素超过 16384 字节；过期删像素留摘要后回到上限；只读首条摘要会答红色。",
    proves: [
      "三条 64×64×3 记录超过字节上限。",
      "过期按写入日删像素，摘要和框仍在。",
      "只读首条杯子摘要会答 red。",
      "改写后的混合策略在预算内答 blue。",
    ],
    doesNotProve: "不证明 LoCoMo、ScreenshotVQA 或家用机器人上的任务成功率，也不能把夹具颜色写成 MIRIX 的 85.4%。",
    sourceFile: "lesson_53.py",
  },
  {
    lessonId: "54",
    purpose: "在四域真实计数 (8000, 800, 200, 50) 上核对：合成灌最大域、补最小域、重复哈希三种账，以及相对位姿变换夹具。",
    proves: [
      "合成只加到最大域时 α=1 的有效域数下降、最大域份额上升",
      "合成补最小域时小域份额从 0.55% 升到 18.6%",
      "重复轨迹不增加唯一哈希，n_eff 从 9050 降到约 30",
      "相对位姿变换保持物体系坐标，写反两个物体位姿会错过物体",
    ],
    doesNotProve: "不证明任何真实机械臂成功率，也不复现 MimicGen 的 5 万条生成或 RoboCasa 的 10 万条预训练。",
    sourceFile: "lesson_54.py",
  },
  {
    lessonId: "55",
    purpose: "用手算同一隐藏向量上三个头的 8/4 bit 量化，确认动作维越过 bin 边界时文本 top-1 仍不变。",
    proves: [
      "8 bit 七维动作箱与全精度相同。",
      "4 bit 时 pitch 从箱 2 跳到箱 1。",
      "4 bit 文本 top-1 仍是标签 0，视觉 L2 上升但粗类未要求跳。",
    ],
    doesNotProve: "不测量手机或 Jetson 上的延迟，也不复现 QVLA 的 1.49× 或 GPTQ 的 3.25×。",
    sourceFile: "lesson_55.py",
  },
  {
    lessonId: "56",
    purpose: "用四张固定像素图证明：过平滑 L2 最低但偏好最低，平移图相反，Kendall τ-a = -1。",
    proves: [
      "L2 序与教学偏好序可以完全相反",
      "过平滑赢像素误差、输 Bradley–Terry",
      "恒等图 L2 为 0，自比较 τ 为 +1",
      "灰均值可以比平移图更近像素，但仍不被偏好",
    ],
    doesNotProve: "不证明 ImageReward、PickScore 或任何视频奖励模型的真实准确率，也不能把夹具分数写成 FID 或 MOS。",
    sourceFile: "lesson_56.py",
  },
  {
    lessonId: "57",
    purpose: "在三条 sidecar 夹具上核对必填字段：缺许可或缺哈希为非法，只有完整行进入训练集。",
    proves: [
      "六项必填字段缺一不可",
      "空许可、unspecified 与未知许可非法",
      "空哈希与哈希不匹配非法",
      "合成标记不能绕过许可",
    ],
    doesNotProve: "不证明任何水印检测率、C2PA 生态覆盖率、真实爬虫合规，也不复现 LAION 或任何生成模型。",
    sourceFile: "lesson_57.py",
  },
  {
    lessonId: "58",
    purpose: "证明医学报告字段的监督集合与自然 caption 不同，并计数空图上的无框肯定",
    proves: [
      "医学 mask 不含 indication / comparison，自然 mask 只含 caption",
      "把自然配方套到报告上会把 indication 误纳入损失",
      "空图关闭无框门控时 U_count=1，打开后门控为 0",
      "开放集 recall=1 不能推出无框计数为 0",
    ],
    doesNotProve: "不证明任何真实医学模型的诊断能力，也不报告真实胸片上的肺炎检出率",
    sourceFile: "lesson_58.py",
  },
  {
    lessonId: "59",
    purpose: "在固定 1280 ms 夹具上核对：语音用词序列算 WER，鼓点用毫秒 onset 算 F1，两类标签不可互换。",
    proves: [
      "词标签与 onset 标签元素类型不同、长度不同。",
      "80 ms 语音网格上 WER = 0 且鼓点 F1 = 2/3 < 0.70。",
      "(1-WER+F1)/2 = 5/6 会在网格已经塌掉时仍显示合格。",
      "20 ms 网格能把 16 个 onset 全部拆开，F1 = 1。",
    ],
    doesNotProve: "不证明 MusicCaps FAD、AudioCaps FD、MUSHRA 或真实 Mimi/EnCodec 重建分数。",
    sourceFile: "lesson_59.py",
  },
  {
    lessonId: "60",
    purpose: "证明收编卡缺 N 或缺套件被拒收，把 LIBERO 写成真机被拒收，且类标签、套件键与第 31、47 课兼容。",
    proves: [
      "必填十个字段；C5 / LIBERO 行还要套件与成功谓词",
      "缺 N、缺套件的准入结果是 reject_incomplete",
      "LIBERO 声称 real_robot 被拒收",
      "第 47 课六类仍互斥，第 31 课四套件键可接受，Wilson 与 N=25、k=20 手算一致",
    ],
    doesNotProve: "不证明任何真实模型的仿真或真机能力，也不能把夹具或虚构表写成 SOTA。",
    sourceFile: "lesson_60.py",
  },
] as const satisfies readonly LessonPractice[];

export const practiceByLessonId = Object.fromEntries(
  practices.map((practice) => [practice.lessonId, practice]),
) as Record<string, LessonPractice>;
