import type { LessonDiagram } from "@/lib/lesson-diagrams/types";

const top = 88;
const bot = 248;
const x = [160, 480, 800] as const;

export const lessonDiagramCatalog: readonly LessonDiagram[] = [
  {
    lessonId: "01",
    title: "V-M-C 三个零件",
    summary: "观察压成状态，按动作预测下一步，再选动作。后面所有课都在换这三件的实现。",
    nodes: [
      { id: "obs", label: ["观察"], meta: "96×96", kind: "input", x: x[0], y: top },
      { id: "v", label: ["V / 压缩"], meta: "VAE", kind: "transform", x: x[1], y: top },
      { id: "z", label: ["状态 z"], kind: "state", x: x[2], y: top },
      { id: "m", label: ["M / 预测"], meta: "MDN-RNN", kind: "transform", x: x[1], y: bot },
      { id: "c", label: ["C / 决策"], kind: "decision", x: x[2], y: bot },
      { id: "act", label: ["动作"], kind: "output", x: x[0], y: bot },
    ],
    edges: [
      { id: "e1", from: "obs", to: "v" },
      { id: "e2", from: "v", to: "z" },
      { id: "e3", from: "z", to: "m" },
      { id: "e4", from: "act", to: "m", label: "动作条件" },
      { id: "e5", from: "m", to: "c" },
      { id: "e6", from: "z", to: "c" },
      { id: "e7", from: "c", to: "act" },
    ],
    steps: [
      { title: "看见", description: "环境给出当前画面。它不是完整状态。", focus: ["obs"] },
      { title: "压缩", description: "V 把画面压成一小串数字 z。", focus: ["obs", "v", "z", "e1", "e2"] },
      { title: "按动作预测", description: "M 吃 z 和打算做的动作，给出下一状态的分布。", focus: ["z", "act", "m", "e3", "e4"] },
      { title: "选动作", description: "C 读状态，吐出转向、油门、刹车。", focus: ["z", "c", "act", "e6", "e7"] },
      { title: "闭环", description: "选中的动作送回环境和 M。梦里训练就是把环境换成 M。", focus: ["m", "c", "act", "e5", "e7"] },
    ],
    facts: [
      "World Models 把系统拆成 V、M、C，对应压缩、预测、控制。",
      "动作必须进入 M，否则预测与规划脱节。",
      "本课缩小配置只验证流程，分数不构成论文复现。",
    ],
  },
  {
    lessonId: "16",
    title: "三条状态路线",
    summary: "重建像素、预测表征、物体中心槽。杯子会不会倒，三种状态的回答能力不同。",
    nodes: [
      { id: "event", label: ["手碰到杯"], kind: "input", x: x[1], y: top },
      { id: "pix", label: ["重建像素"], kind: "transform", x: x[0], y: bot },
      { id: "jepa", label: ["预测表征"], kind: "transform", x: x[1], y: bot },
      { id: "slot", label: ["物体槽"], kind: "state", x: x[2], y: bot },
      { id: "ask", label: ["杯子会倒吗"], kind: "decision", x: x[2], y: top },
    ],
    edges: [
      { id: "e1", from: "event", to: "pix" },
      { id: "e2", from: "event", to: "jepa" },
      { id: "e3", from: "event", to: "slot" },
      { id: "e4", from: "pix", to: "ask" },
      { id: "e5", from: "jepa", to: "ask" },
      { id: "e6", from: "slot", to: "ask" },
    ],
    steps: [
      { title: "同一件事", description: "手碰到一杯水。三种路线吃的是同一段观察。", focus: ["event"] },
      { title: "重建", description: "像素路线能画出水花，杯子和手糊在一张图里。", focus: ["event", "pix", "e1"] },
      { title: "表征", description: "JEPA 可能知道接触发生了，但没有单独的杯子变量。", focus: ["event", "jepa", "e2"] },
      { title: "槽", description: "杯子、手、桌子分槽。问杯子槽的下一姿态即可。", focus: ["event", "slot", "e3"] },
      { title: "谁能回答", description: "规划要的是可操作的状态，不是更好看的下一帧。", focus: ["ask", "slot", "e6"] },
    ],
    facts: [
      "第三条路是物体中心槽，不是社区口碑场。",
      "C-SWM 的真实验在第 23 课。",
      "判断必须写成：在世界域 X、验证者 Y、实验 Z 下观察到什么。",
    ],
  },
  {
    lessonId: "21",
    title: "持久状态怎么更新",
    summary: "新帧进来，改写同一份 3D 状态。挡住不等于消失；端走才应该更新。",
    nodes: [
      { id: "frame", label: ["新的一帧"], kind: "input", x: x[0], y: top },
      { id: "prev", label: ["s t-1"], kind: "state", x: x[1], y: top },
      { id: "upd", label: ["状态更新"], kind: "transform", x: x[1], y: bot },
      { id: "now", label: ["s t"], kind: "state", x: x[2], y: bot },
      { id: "lamp", label: ["恒常灯"], kind: "output", x: x[2], y: top },
      { id: "actn", label: ["动作？无"], kind: "decision", x: x[0], y: bot },
    ],
    edges: [
      { id: "e1", from: "frame", to: "upd" },
      { id: "e2", from: "prev", to: "upd" },
      { id: "e3", from: "upd", to: "now" },
      { id: "e4", from: "now", to: "lamp" },
      { id: "e5", from: "now", to: "prev", label: "下一拍" },
      { id: "e6", from: "actn", to: "upd" },
    ],
    steps: [
      { title: "来了一帧", description: "摄像头或绕行视频给出新观察。", focus: ["frame"] },
      { title: "带着旧状态", description: "CUT3R 内部带着上一拍的 token，不是把所有图重推一遍。", focus: ["prev", "upd", "e2"] },
      { title: "写进去", description: "新图编成 token，与旧状态交互，得到 s_t。", focus: ["frame", "upd", "now", "e1", "e3"] },
      { title: "灯", description: "杯子若还在状态里，灯绿。挡住应绿，端走应红。", focus: ["now", "lamp", "e4"] },
      { title: "还不是世界模型", description: "这条递归没有动作端口。它更新几何，不预测伸手之后。", focus: ["actn", "upd", "e6"] },
    ],
    facts: [
      "VGGT 吃图集合，CUT3R 吃图序列。",
      "物体恒常测的是状态，不是渲染是否好看。",
      "没有 a_t 的模型不能回答杯子被推到哪。",
    ],
  },
  {
    lessonId: "30",
    title: "桌子上的动作条件模型",
    summary: "同一帧，看左和伸手必须给出不同的下一状态。这是桌宠的小脑。",
    nodes: [
      { id: "desk", label: ["桌面观察"], kind: "input", x: x[0], y: top },
      { id: "st", label: ["状态"], kind: "state", x: x[1], y: top },
      { id: "a", label: ["动作"], kind: "input", x: x[0], y: bot },
      { id: "dyn", label: ["动力学"], kind: "transform", x: x[1], y: bot },
      { id: "fut", label: ["下一状态"], kind: "state", x: x[2], y: bot },
      { id: "swap", label: ["动作对换"], kind: "decision", x: x[2], y: top },
    ],
    edges: [
      { id: "e1", from: "desk", to: "st" },
      { id: "e2", from: "st", to: "dyn" },
      { id: "e3", from: "a", to: "dyn" },
      { id: "e4", from: "dyn", to: "fut" },
      { id: "e5", from: "fut", to: "swap" },
      { id: "e6", from: "a", to: "swap", label: "换动作" },
    ],
    steps: [
      { title: "看见桌子", description: "摄像头档用键盘当假身体，真机档用关节命令。", focus: ["desk", "st", "e1"] },
      { title: "加上动作", description: "看左、看右、伸手、不动，必须作为输入。", focus: ["a", "dyn", "e3"] },
      { title: "预测下一步", description: "小模型即可：RSSM、特征动力学或槽动力学，复用前面课。", focus: ["st", "dyn", "fut", "e2", "e4"] },
      { title: "对换", description: "同一历史只换动作。杯子或头的下一刻必须不同。", focus: ["swap", "fut", "a", "e5", "e6"] },
      { title: "负对照", description: "动作置零或打乱后应对换失败。否则你还没证明模型在看动作。", focus: ["a", "swap", "e6"] },
    ],
    facts: [
      "复现 #9 的主证据是动作对换必须分岔。",
      "禁止只用重建损失、不管动作。",
      "多步漂移曲线要单独报，不能用一步误差代替。",
    ],
  },
  {
    lessonId: "32",
    title: "先想再做",
    summary: "感知、世界模型、安全层、执行。五件毕业行为每件都要走过这一圈。",
    nodes: [
      { id: "sense", label: ["感知"], kind: "input", x: x[0], y: top },
      { id: "st", label: ["状态+记忆"], kind: "state", x: x[1], y: top },
      { id: "wm", label: ["展开未来"], kind: "transform", x: x[2], y: top },
      { id: "safe", label: ["安全过滤"], kind: "decision", x: x[1], y: bot },
      { id: "body", label: ["身体/屏幕"], kind: "output", x: x[2], y: bot },
      { id: "human", label: ["对面的人"], kind: "input", x: x[0], y: bot },
    ],
    edges: [
      { id: "e1", from: "sense", to: "st" },
      { id: "e2", from: "human", to: "st" },
      { id: "e3", from: "st", to: "wm" },
      { id: "e4", from: "wm", to: "safe" },
      { id: "e5", from: "safe", to: "body" },
      { id: "e6", from: "body", to: "human", label: "真实后果" },
    ],
    steps: [
      { title: "看", description: "杯子、人脸朝向、自己的关节。像素不是状态。", focus: ["sense", "st", "e1"] },
      { title: "人", description: "人是外生过程。预测会不会看过来，但不把人当成可下发的动作。", focus: ["human", "st", "e2"] },
      { title: "想", description: "用第 30 课的模型展开几条未来。", focus: ["st", "wm", "e3"] },
      { title: "克制", description: "轨迹过桌沿就截断。没有安全层不准上真机。", focus: ["wm", "safe", "e4"] },
      { title: "做或停", description: "摄像头档用屏幕朝向代替物理动作，查询不能省。", focus: ["safe", "body", "human", "e5", "e6"] },
    ],
    facts: [
      "五件行为：恒常、对视、克制、对换展示、失败承认。",
      "没有调用世界模型的行为记零。",
      "买 Reachy Mini 或 SO-101 不是及格条件。",
    ],
  },
  {
    lessonId: "33",
    title: "具身程度 E0 到 E5",
    summary: "升级只看是否题。有身体不等于用了世界模型，会聊天不升档。",
    nodes: [
      { id: "e0", label: ["E0 无动作"], kind: "input", x: 160, y: 88 },
      { id: "e1", label: ["E1 离线条件"], kind: "transform", x: 480, y: 88 },
      { id: "e2", label: ["E2 可重置"], kind: "state", x: 800, y: 88 },
      { id: "e3", label: ["E3 开环真机"], kind: "output", x: 160, y: 248 },
      { id: "e4", label: ["E4 模型在回路"], kind: "decision", x: 480, y: 248 },
      { id: "e5", label: ["E5 不可暂停"], kind: "state", x: 800, y: 248 },
    ],
    edges: [
      { id: "e01", from: "e0", to: "e1", label: "动作对换" },
      { id: "e12", from: "e1", to: "e2", label: "接到环境" },
      { id: "e13", from: "e1", to: "e3", label: "真机但开环" },
      { id: "e24", from: "e2", to: "e4" },
      { id: "e34", from: "e3", to: "e4", label: "查询模型" },
      { id: "e45", from: "e4", to: "e5", label: "时间/他者/接触" },
    ],
    steps: [
      { title: "先问动作", description: "对换不分岔，停在 E0。好看的视频也一样。", focus: ["e0", "e1", "e01"] },
      { title: "离线还是可重置", description: "梦里规划是 E1。gym 里失败可 reset，是 E2。", focus: ["e1", "e2", "e12"] },
      { title: "真机开环", description: "ACT / VLA 有身体，选动作时不查询前向模型，是 E3。", focus: ["e1", "e3", "e13"] },
      { title: "模型进回路", description: "展开未来或安全过滤之后才执行，才是 E4。", focus: ["e3", "e4", "e2", "e34", "e24"] },
      { title: "不可暂停", description: "真实时间、接触代价、不可控的人、停下算成功，才写 E5。", focus: ["e4", "e5", "e45"] },
    ],
    facts: [
      "E0 到 E5 是本课作业口径，不替换 Wilson 或 Ziemke 的分类。",
      "真机成功可以把系统送到 E3，送到 E4 必须有世界模型查询日志。",
      "聊天、表情、参数量都不升档。",
    ],
  },
  {
    lessonId: "34",
    title: "三份榜不是同一根尺子",
    summary: "WorldScore 测下一场景，WorldModelBench 测视频当世界模型用，Physics-IQ 测物理续写。规划另算。",
    nodes: [
      { id: "sys", label: ["候选系统"], kind: "input", x: x[0], y: top },
      { id: "ws", label: ["WorldScore"], kind: "transform", x: x[1], y: top },
      { id: "wmb", label: ["WorldModelBench"], kind: "transform", x: x[2], y: top },
      { id: "piq", label: ["Physics-IQ"], kind: "state", x: x[0], y: bot },
      { id: "swap", label: ["动作对换"], kind: "decision", x: x[1], y: bot },
      { id: "plan", label: ["规划"], kind: "output", x: x[2], y: bot },
    ],
    edges: [
      { id: "e1", from: "sys", to: "ws" },
      { id: "e2", from: "sys", to: "wmb" },
      { id: "e3", from: "sys", to: "piq" },
      { id: "e4", from: "ws", to: "plan", label: "不自动" },
      { id: "e5", from: "wmb", to: "swap" },
      { id: "e6", from: "piq", to: "swap" },
      { id: "e7", from: "swap", to: "plan" },
    ],
    steps: [
      { title: "先放进哪份榜", description: "同一个名字可以同时上三份榜。", focus: ["sys", "ws", "wmb", "e1", "e2"] },
      { title: "生成真", description: "WorldScore 问下一场景好不好看、能不能控。", focus: ["ws", "plan", "e4"] },
      { title: "续写对不对", description: "Physics-IQ 和真实实验录像比，不管观感。", focus: ["piq", "e3", "e6"] },
      { title: "桌宠要的", description: "对换分岔之后才能规划。", focus: ["swap", "plan", "e7"] },
    ],
    facts: [
      "没测过的格子写未测。官方宣传写宣称。",
      "Genie 3 与 GAIA-2 无权重，不能练。",
      "WorldScore 第一名不必能给桌宠做 MPC。",
    ],
  },
  {
    lessonId: "35",
    title: "Cosmos 3 两条通路",
    summary: "Reasoner 因果理解，Generator 去噪生成。输入输出组合决定它像哪种产品。",
    nodes: [
      { id: "in", label: ["多模态输入"], kind: "input", x: x[0], y: top },
      { id: "reason", label: ["Reasoner"], meta: "因果", kind: "decision", x: x[1], y: top },
      { id: "gen", label: ["Generator"], meta: "去噪", kind: "transform", x: x[1], y: bot },
      { id: "text", label: ["语言"], kind: "output", x: x[2], y: top },
      { id: "media", label: ["像素 / 声"], kind: "output", x: x[2], y: bot },
      { id: "act", label: ["动作"], kind: "state", x: x[0], y: bot },
    ],
    edges: [
      { id: "e1", from: "in", to: "reason" },
      { id: "e2", from: "in", to: "gen" },
      { id: "e3", from: "act", to: "gen", label: "可选条件" },
      { id: "e4", from: "reason", to: "text" },
      { id: "e5", from: "gen", to: "media" },
      { id: "e6", from: "gen", to: "act" },
    ],
    steps: [
      { title: "进", description: "语言、图像、视频、声音、动作都只是通道。", focus: ["in", "act"] },
      { title: "理解", description: "Reasoner 走因果注意力，出的是话。", focus: ["in", "reason", "text", "e1", "e4"] },
      { title: "生成", description: "Generator 对噪声 token 去噪。", focus: ["in", "gen", "media", "e2", "e5"] },
      { title: "动作", description: "动作可以当条件，也可以当输出。两件事不要混。", focus: ["act", "gen", "e3", "e6"] },
    ],
    facts: [
      "Predict2.5 是视频基础模型，不是 Cosmos 3。",
      "Nano 推理官方约 32GB，主线 24GB 不够就只讲。",
      "Artificial Analysis / RoboArena 排名是宣称，不是本课复现。",
    ],
  },
  {
    lessonId: "36",
    title: "声音进观察，不是配乐",
    summary: "麦克风是 o_t。同一画面换声轨，下一秒必须允许分岔。",
    nodes: [
      { id: "rgb", label: ["画面"], kind: "input", x: x[0], y: top },
      { id: "wav", label: ["声轨"], kind: "input", x: x[0], y: bot },
      { id: "obs", label: ["视听观察"], kind: "state", x: x[1], y: top },
      { id: "wm", label: ["世界模型"], kind: "transform", x: x[1], y: bot },
      { id: "next", label: ["下一秒"], kind: "output", x: x[2], y: top },
      { id: "bgm", label: ["BGM"], kind: "decision", x: x[2], y: bot },
    ],
    edges: [
      { id: "e1", from: "rgb", to: "obs" },
      { id: "e2", from: "wav", to: "obs" },
      { id: "e3", from: "obs", to: "wm" },
      { id: "e4", from: "wm", to: "next" },
      { id: "e5", from: "bgm", to: "next", label: "不该改动力学" },
      { id: "e6", from: "wav", to: "wm", label: "对换" },
    ],
    steps: [
      { title: "钉死画面", description: "杯子停在桌沿。只换声轨。", focus: ["rgb", "wav"] },
      { title: "观察", description: "AVWM 把声和画一起写成 o_t。", focus: ["rgb", "wav", "obs", "e1", "e2"] },
      { title: "对换", description: "杯碰桌沿和键盘，下一秒必须允许分岔。", focus: ["wav", "wm", "next", "e6", "e4"] },
      { title: "配乐", description: "BGM 对不齐事件，不该改杯子会不会倒。", focus: ["bgm", "next", "e5"] },
    ],
    facts: [
      "Reachy Mini 的麦克风是观察，喇叭可以是动作。",
      "Veo / Sora 2 / Kling 的音画产品标成只讲。",
      "AVWM 无官方训练仓库，不要假装有。",
    ],
  },
  {
    lessonId: "37",
    title: "训练时看谁，推理时接谁",
    summary: "teacher forcing 喂真值。self-forcing 喂自己。双向扩散一次看整段。",
    nodes: [
      { id: "data", label: ["真历史"], kind: "input", x: x[0], y: top },
      { id: "model", label: ["生成器"], kind: "transform", x: x[1], y: top },
      { id: "self", label: ["自己的输出"], kind: "state", x: x[0], y: bot },
      { id: "future", label: ["下一帧"], kind: "output", x: x[2], y: top },
      { id: "bidiff", label: ["双向整段"], kind: "decision", x: x[2], y: bot },
      { id: "kv", label: ["KV cache"], kind: "transform", x: x[1], y: bot },
    ],
    edges: [
      { id: "e1", from: "data", to: "model", label: "teacher forcing" },
      { id: "e2", from: "self", to: "kv" },
      { id: "e3", from: "kv", to: "model", label: "self-forcing" },
      { id: "e4", from: "model", to: "future" },
      { id: "e5", from: "future", to: "self" },
      { id: "e6", from: "bidiff", to: "future", label: "不能中途改动作" },
    ],
    steps: [
      { title: "喂真值", description: "训练损失好看，推理会脱节。", focus: ["data", "model", "e1"] },
      { title: "自己接自己", description: "训练时走 KV cache，对准推理分布。", focus: ["self", "kv", "model", "e2", "e3"] },
      { title: "滚下去", description: "输出再进状态，误差才会被看见。", focus: ["model", "future", "self", "e4", "e5"] },
      { title: "整段去噪", description: "画质高，但不能边看边播。", focus: ["bidiff", "future", "e6"] },
    ],
    facts: [
      "第 03 课 MDN-RNN 就能演示曝光偏差。",
      "不要编造 VBench 分数。",
      "Self-Forcing 推理官方至少 24GB；不够就停并写失败原因。",
    ],
  },
  {
    lessonId: "38",
    title: "骨架决定状态在哪",
    summary: "AR、DiT、MoT、JEPA、RSSM、latent action 把状态放在不同的地方。",
    nodes: [
      { id: "obs", label: ["观察"], kind: "input", x: x[0], y: top },
      { id: "enc", label: ["编码器"], kind: "transform", x: x[1], y: top },
      { id: "st", label: ["状态"], kind: "state", x: x[2], y: top },
      { id: "dyn", label: ["动力学"], kind: "transform", x: x[1], y: bot },
      { id: "act", label: ["动作"], kind: "input", x: x[0], y: bot },
      { id: "out", label: ["未来"], kind: "output", x: x[2], y: bot },
    ],
    edges: [
      { id: "e1", from: "obs", to: "enc" },
      { id: "e2", from: "enc", to: "st" },
      { id: "e3", from: "st", to: "dyn" },
      { id: "e4", from: "act", to: "dyn" },
      { id: "e5", from: "dyn", to: "out" },
      { id: "e6", from: "dyn", to: "st", label: "滚动" },
    ],
    steps: [
      { title: "压", description: "观察先进编码器。VGGT 停在这里。", focus: ["obs", "enc", "e1"] },
      { title: "状态", description: "RSSM 是向量，IRIS 是 token，JEPA 是表征。", focus: ["enc", "st", "e2"] },
      { title: "听动作", description: "动作必须进动力学，否则是画师。", focus: ["act", "dyn", "st", "e3", "e4"] },
      { title: "展开", description: "滚动未来，才能规划。", focus: ["dyn", "out", "st", "e5", "e6"] },
    ],
    facts: [
      "Transformer 不是一种世界模型。",
      "3DGS 不是动力学。",
      "选型要写 24GB 能不能跑。",
    ],
  },
  {
    lessonId: "39",
    title: "三种忘法",
    summary: "滑窗丢掉 K 帧前。隐状态会漂。记忆库按位姿取回。",
    nodes: [
      { id: "now", label: ["当前帧"], kind: "input", x: x[0], y: top },
      { id: "win", label: ["滑窗 K"], kind: "transform", x: x[1], y: top },
      { id: "hid", label: ["压缩状态"], kind: "state", x: x[2], y: top },
      { id: "bank", label: ["记忆库"], kind: "decision", x: x[1], y: bot },
      { id: "pose", label: ["位姿 / 时刻"], kind: "input", x: x[0], y: bot },
      { id: "cup", label: ["杯子还在?"], kind: "output", x: x[2], y: bot },
    ],
    edges: [
      { id: "e1", from: "now", to: "win" },
      { id: "e2", from: "win", to: "cup", label: "K 外丢掉" },
      { id: "e3", from: "now", to: "hid" },
      { id: "e4", from: "hid", to: "cup", label: "会漂" },
      { id: "e5", from: "pose", to: "bank" },
      { id: "e6", from: "bank", to: "cup", label: "按键取回" },
    ],
    steps: [
      { title: "走开", description: "杯子离开当前帧。", focus: ["now", "cup"] },
      { title: "滑窗", description: "窗口罩不住就现编。第 12 课量过。", focus: ["now", "win", "cup", "e1", "e2"] },
      { title: "隐状态", description: "记得有过杯子，位置可能已经错了。", focus: ["hid", "cup", "e3", "e4"] },
      { title: "记忆库", description: "用位姿当查询键，而不是指望窗口还罩着。", focus: ["pose", "bank", "cup", "e5", "e6"] },
    ],
    facts: [
      "Genie 3 的数分钟一致性是宣称。",
      "CUT3R 的 4D 状态更新不是生成式记忆库。",
      "记忆本身不升具身档。",
    ],
  },
  {
    lessonId: "40",
    title: "后训练流水线",
    summary: "视频预训练之后，必须加动作通道、做对换，才能接到规划和安全层。",
    nodes: [
      { id: "pt", label: ["视频预训练"], kind: "input", x: x[0], y: top },
      { id: "act", label: ["动作通道"], kind: "transform", x: x[1], y: top },
      { id: "swap", label: ["动作对换"], kind: "decision", x: x[2], y: top },
      { id: "plan", label: ["规划"], kind: "transform", x: x[1], y: bot },
      { id: "safe", label: ["安全层"], kind: "state", x: x[2], y: bot },
      { id: "body", label: ["身体"], kind: "output", x: x[0], y: bot },
    ],
    edges: [
      { id: "e1", from: "pt", to: "act" },
      { id: "e2", from: "act", to: "swap" },
      { id: "e3", from: "swap", to: "plan" },
      { id: "e4", from: "plan", to: "safe" },
      { id: "e5", from: "safe", to: "body" },
      { id: "e6", from: "swap", to: "body", label: "分岔失败则停" },
    ],
    steps: [
      { title: "预训练", description: "互联网视频只给画师。", focus: ["pt"] },
      { title: "加动作", description: "文本条件不算动作通道。", focus: ["pt", "act", "e1"] },
      { title: "对换", description: "不分岔就不要进规划。", focus: ["act", "swap", "e2", "e6"] },
      { title: "闸", description: "能规划仍不能直接上真机。", focus: ["plan", "safe", "body", "e4", "e5"] },
    ],
    facts: [
      "Cosmos Policy 更接近 π(a|s)，不是 P(s'|s,a)。",
      "DINO-WM 的动作通道在第 22 课已经核过。",
      "第 30 课是这条流水线的桌面缩小版。",
    ],
  },
  {
    lessonId: "41",
    title: "驾驶条件怎么拆",
    summary: "自车是动作，他车是外生，天气是风格。验证者是路。",
    nodes: [
      { id: "ego", label: ["自车转向"], kind: "input", x: x[0], y: top },
      { id: "other", label: ["他车 / 行人"], kind: "state", x: x[1], y: top },
      { id: "wx", label: ["天气"], kind: "transform", x: x[2], y: top },
      { id: "map", label: ["道路语义"], kind: "state", x: x[0], y: bot },
      { id: "gen", label: ["多相机生成"], kind: "transform", x: x[1], y: bot },
      { id: "val", label: ["路"], kind: "output", x: x[2], y: bot },
    ],
    edges: [
      { id: "e1", from: "ego", to: "gen", label: "动作" },
      { id: "e2", from: "other", to: "gen", label: "外生" },
      { id: "e3", from: "wx", to: "gen", label: "条件" },
      { id: "e4", from: "map", to: "gen" },
      { id: "e5", from: "gen", to: "val" },
      { id: "e6", from: "ego", to: "val" },
    ],
    steps: [
      { title: "动作", description: "自车速度和转向，规划器选得了。", focus: ["ego", "e1"] },
      { title: "外生", description: "对向来车选不了，只能预测。", focus: ["other", "gen", "e2"] },
      { title: "风格", description: "下雨不是方向盘能关掉的。", focus: ["wx", "map", "gen", "e3", "e4"] },
      { title: "验证者", description: "开环合成数据生成器通常是 E0 或 E1。", focus: ["gen", "val", "ego", "e5", "e6"] },
    ],
    facts: [
      "GAIA-2/3 无公开权重，只讲。",
      "Cosmos Transfer AV 是域适应，不一定是世界模型。",
      "本课不训车。",
    ],
  },
  {
    lessonId: "42",
    title: "三套头不要焊死",
    summary: "理解头说话，生成头播未来，动作头吐控制。杯子会不会倒要问前向模型。",
    nodes: [
      { id: "obs", label: ["观察 / 指令"], kind: "input", x: x[0], y: top },
      { id: "reason", label: ["理解头"], kind: "decision", x: x[1], y: top },
      { id: "gen", label: ["生成头"], kind: "transform", x: x[1], y: bot },
      { id: "pi", label: ["动作头"], kind: "output", x: x[2], y: top },
      { id: "wm", label: ["前向模型"], kind: "state", x: x[0], y: bot },
      { id: "gate", label: ["过滤器"], kind: "decision", x: x[2], y: bot },
    ],
    edges: [
      { id: "e1", from: "obs", to: "reason" },
      { id: "e2", from: "obs", to: "pi" },
      { id: "e3", from: "obs", to: "gen" },
      { id: "e4", from: "pi", to: "wm" },
      { id: "e5", from: "wm", to: "gate" },
      { id: "e6", from: "gate", to: "pi", label: "截断扫杯" },
    ],
    steps: [
      { title: "理解", description: "杯子是什么、指令是什么。", focus: ["obs", "reason", "e1"] },
      { title: "提议", description: "VLA / π0 默认 E3。", focus: ["obs", "pi", "e2"] },
      { title: "询问未来", description: "生成头或第 30 课模型回答会不会倒。", focus: ["gen", "wm", "e3", "e4"] },
      { title: "改写", description: "过滤器动了动作，才进 E4。", focus: ["wm", "gate", "pi", "e5", "e6"] },
    ],
    facts: [
      "RoboArena 第一不能写成桌宠可迁移。",
      "GR00T N1.7 当前公开材料按 VLA 读。",
      "桌宠最小接入：策略提议，世界模型过滤。",
    ],
  },
  {
    lessonId: "43",
    title: "可玩要过四项",
    summary: "流式、延迟、回头一致、动作对换。网页流畅不是实测 24 fps。",
    nodes: [
      { id: "prompt", label: ["文本 / 首帧"], kind: "input", x: x[0], y: top },
      { id: "stream", label: ["流式生成"], kind: "transform", x: x[1], y: top },
      { id: "ctrl", label: ["玩家动作"], kind: "input", x: x[0], y: bot },
      { id: "mem", label: ["回头记忆"], kind: "state", x: x[1], y: bot },
      { id: "swap", label: ["动作对换"], kind: "decision", x: x[2], y: bot },
      { id: "play", label: ["可玩世界"], kind: "output", x: x[2], y: top },
    ],
    edges: [
      { id: "e1", from: "prompt", to: "stream" },
      { id: "e2", from: "ctrl", to: "stream" },
      { id: "e3", from: "stream", to: "play" },
      { id: "e4", from: "mem", to: "play" },
      { id: "e5", from: "ctrl", to: "swap" },
      { id: "e6", from: "swap", to: "play" },
    ],
    steps: [
      { title: "播", description: "不能等整段算完。", focus: ["prompt", "stream", "play", "e1", "e3"] },
      { title: "玩", description: "动作延迟太大就像幻灯片。", focus: ["ctrl", "stream", "e2"] },
      { title: "回头", description: "转身再回来还认得，才有世界。", focus: ["mem", "play", "e4"] },
      { title: "对换", description: "看起来可玩，仍可能动作盲。", focus: ["ctrl", "swap", "play", "e5", "e6"] },
    ],
    facts: [
      "Genie 3 无权重，24 fps 是宣称。",
      "open-oasis 崩坏引用第 12 课，不重测。",
      "HY-World 是 3D 资产生成，不是视频交互世界模型。",
    ],
  },
  {
    lessonId: "44",
    title: "画面真、物理对、规划好",
    summary: "三根尺子可以互相矛盾。Physics-IQ 测续写，不是规划成功率。",
    nodes: [
      { id: "exp", label: ["真实实验"], kind: "input", x: x[0], y: top },
      { id: "ctx", label: ["前文"], kind: "state", x: x[1], y: top },
      { id: "gen", label: ["模型续写"], kind: "transform", x: x[2], y: top },
      { id: "look", label: ["画面真"], kind: "output", x: x[0], y: bot },
      { id: "phys", label: ["Physics-IQ"], kind: "decision", x: x[1], y: bot },
      { id: "plan", label: ["规划"], kind: "output", x: x[2], y: bot },
    ],
    edges: [
      { id: "e1", from: "exp", to: "ctx" },
      { id: "e2", from: "ctx", to: "gen" },
      { id: "e3", from: "gen", to: "look" },
      { id: "e4", from: "gen", to: "phys" },
      { id: "e5", from: "exp", to: "phys", label: "真实续写" },
      { id: "e6", from: "phys", to: "plan", label: "不自动" },
    ],
    steps: [
      { title: "前文", description: "模型只看到实验开头。", focus: ["exp", "ctx", "e1"] },
      { title: "续写", description: "生成后文，观感可以很好。", focus: ["ctx", "gen", "look", "e2", "e3"] },
      { title: "对照录像", description: "和真实续写比重合。", focus: ["exp", "gen", "phys", "e4", "e5"] },
      { title: "别跨尺子", description: "续写对了，也不等于能选动作。", focus: ["phys", "plan", "e6"] },
    ],
    facts: [
      "论文结论：视觉真实感和物理理解可以脱钩。",
      "分数只抄论文表或仓库 README。",
      "杯子会不会下桌，不能用生成视频好不好看来代替。",
    ],
  },
  {
    lessonId: "45",
    title: "带走一块，带回桌子",
    summary: "目标函数决定在哪根尺子上好看。第九幕只改第 30 课的一个零件。",
    nodes: [
      { id: "obj", label: ["目标函数"], kind: "input", x: x[0], y: top },
      { id: "ruler", label: ["生成 / 物理 / 对换"], kind: "decision", x: x[1], y: top },
      { id: "pick", label: ["只选一块"], kind: "transform", x: x[2], y: top },
      { id: "desk", label: ["第 30 课模型"], kind: "state", x: x[1], y: bot },
      { id: "swap", label: ["动作对换"], kind: "output", x: x[0], y: bot },
      { id: "grad", label: ["毕业 32 / 33"], kind: "output", x: x[2], y: bot },
    ],
    edges: [
      { id: "e1", from: "obj", to: "ruler" },
      { id: "e2", from: "ruler", to: "pick" },
      { id: "e3", from: "pick", to: "desk" },
      { id: "e4", from: "desk", to: "swap" },
      { id: "e5", from: "desk", to: "grad" },
      { id: "e6", from: "pick", to: "grad", label: "不是第二场毕业" },
    ],
    steps: [
      { title: "目标", description: "重建、JEPA、flow、self-forcing 各赌一根尺子。", focus: ["obj", "ruler", "e1"] },
      { title: "只选一块", description: "24GB 搬不走 Cosmos 3。", focus: ["ruler", "pick", "e2"] },
      { title: "改桌子", description: "动作对换和物体恒常说了算。", focus: ["pick", "desk", "swap", "e3", "e4"] },
      { title: "毕业仍在原处", description: "第 32 课总装，第 33 课打档。", focus: ["desk", "grad", "pick", "e5", "e6"] },
    ],
    facts: [
      "做不成改造就写失败报告，仍算完成本课。",
      "禁止后训练 Cosmos 3 当作业。",
      "刷榜分数默认测生成真。",
    ],
  },
];
