import type { LessonDiagram } from "@/lib/lesson-diagrams/types";

export const foundationDiagrams: LessonDiagram[] = [
  {
    lessonId: "01",
    title: "MiniMind-O 基线中的可追溯计算链",
    summary:
      "从数据行到文本与语音输出，逐段锁定 target、hidden state、codec code 和时间戳。",
    viewBox: "0 0 960 360",
    nodes: [
      {
        id: "l01-sample",
        label: ["训练数据行"],
        meta: "text / audio / image",
        kind: "input",
        x: 82,
        y: 170,
      },
      {
        id: "l01-layout",
        label: ["九路训练布局"],
        meta: "8 audio + 1 text",
        kind: "transform",
        x: 250,
        y: 170,
      },
      {
        id: "l01-thinker",
        label: ["Thinker"],
        meta: "8 layers",
        kind: "transform",
        x: 435,
        y: 92,
      },
      {
        id: "l01-text",
        label: ["文本 logits"],
        meta: "assistant mask",
        kind: "output",
        x: 625,
        y: 62,
      },
      {
        id: "l01-bridge",
        label: ["中间层 bridge"],
        meta: "hidden → Talker",
        kind: "state",
        x: 435,
        y: 248,
      },
      {
        id: "l01-talker",
        label: ["Talker"],
        meta: "4 layers / 8 heads",
        kind: "transform",
        x: 625,
        y: 248,
      },
      {
        id: "l01-pcm",
        label: ["Mimi 解码", "24 kHz PCM"],
        meta: "首个可播放 chunk",
        kind: "output",
        x: 850,
        y: 248,
        width: 160,
      },
    ],
    edges: [
      {
        id: "l01-e-sample-layout",
        from: "l01-sample",
        to: "l01-layout",
        label: "构造 mask 与 delay",
        labelAt: { x: 166, y: 218 },
      },
      {
        id: "l01-e-layout-thinker",
        from: "l01-layout",
        to: "l01-thinker",
        label: "第 9 路 + 模态特征",
        via: [{ x: 335, y: 170 }, { x: 335, y: 92 }],
        labelAt: { x: 280, y: 126 },
      },
      {
        id: "l01-e-thinker-text",
        from: "l01-thinker",
        to: "l01-text",
        label: "next-token",
        labelAt: { x: 530, y: 20 },
      },
      {
        id: "l01-e-thinker-bridge",
        from: "l01-thinker",
        to: "l01-bridge",
        label: "middle hidden",
      },
      {
        id: "l01-e-layout-talker",
        from: "l01-layout",
        to: "l01-talker",
        label: "历史 codec / speaker",
        via: [{ x: 330, y: 300 }, { x: 530, y: 300 }],
        labelAt: { x: 430, y: 318 },
      },
      {
        id: "l01-e-bridge-talker",
        from: "l01-bridge",
        to: "l01-talker",
        label: "语义条件",
      },
      {
        id: "l01-e-talker-pcm",
        from: "l01-talker",
        to: "l01-pcm",
        label: "8 codes / frame",
      },
    ],
    steps: [
      {
        title: "固定输入与 target",
        description:
          "数据行先展开为 8 路 Mimi code 和 1 路文本；assistant 之外的位置不参与目标 loss。",
        focus: ["l01-sample", "l01-layout", "l01-e-sample-layout"],
      },
      {
        title: "计算文本路径",
        description:
          "Thinker 接收文本及已注入的模态特征，文本 head 只在 assistant target 上计算 next-token loss。",
        focus: [
          "l01-layout",
          "l01-thinker",
          "l01-text",
          "l01-e-layout-thinker",
          "l01-e-thinker-text",
        ],
      },
      {
        title: "读取 bridge",
        description:
          "指定中间层 hidden state 经投影后成为 Talker 的语义条件；它与历史 codec 条件分开记录。",
        focus: [
          "l01-thinker",
          "l01-bridge",
          "l01-e-thinker-bridge",
        ],
      },
      {
        title: "生成并重组八码本",
        description:
          "Talker 预测 diagonal-delay 序列；只有凑齐同一帧的 8 个 code 后才能交给 Mimi。",
        focus: [
          "l01-layout",
          "l01-bridge",
          "l01-talker",
          "l01-e-layout-talker",
          "l01-e-bridge-talker",
        ],
      },
      {
        title: "以 PCM 定义可播放延迟",
        description:
          "TTFA 的终点是首个可播放 PCM chunk，而不是首个 codec logit 或未完成的 codec frame。",
        focus: ["l01-talker", "l01-pcm", "l01-e-talker-pcm"],
      },
    ],
    facts: [
      "MiniMind-O 训练布局包含 8 路音频 code 和 1 路文本。",
      "Thinker 的中间层 hidden state 经 bridge 连接到 Talker。",
      "trace 开关必须保持 logits、随机数状态和最终输出不变。",
      "Mimi 基线使用 8 个码本并输出 24 kHz PCM。",
    ],
  },
  {
    lessonId: "02",
    title: "Connector 的三种信息压缩路径",
    summary:
      "固定 encoder features 与 Thinker，比较逐 token MLP 和两种 learned-query connector。",
    viewBox: "0 0 960 360",
    nodes: [
      {
        id: "l02-features",
        label: ["冻结 encoder", "features"],
        meta: "[B, Tin, Din]",
        kind: "input",
        x: 90,
        y: 180,
        width: 156,
      },
      {
        id: "l02-mlp",
        label: ["两层 MLP"],
        meta: "Tout = Tin",
        kind: "transform",
        x: 300,
        y: 68,
      },
      {
        id: "l02-resampler",
        label: ["Perceiver", "Resampler"],
        meta: "Tout = Q",
        kind: "transform",
        x: 300,
        y: 180,
      },
      {
        id: "l02-qformer",
        label: ["轻量 Q-Former"],
        meta: "self + cross attention",
        kind: "transform",
        x: 300,
        y: 292,
      },
      {
        id: "l02-tokens",
        label: ["LLM 输入 tokens"],
        meta: "[B, Tout, 768]",
        kind: "state",
        x: 535,
        y: 180,
      },
      {
        id: "l02-thinker",
        label: ["冻结 Thinker"],
        meta: "同一文本 head",
        kind: "transform",
        x: 720,
        y: 180,
      },
      {
        id: "l02-probe",
        label: ["模态依赖检查"],
        meta: "correct / zero / shuffle",
        kind: "output",
        x: 880,
        y: 180,
        width: 148,
      },
    ],
    edges: [
      {
        id: "l02-e-features-mlp",
        from: "l02-features",
        to: "l02-mlp",
        label: "逐 token 投影",
        via: [{ x: 190, y: 180 }, { x: 190, y: 68 }],
        labelAt: { x: 192, y: 112 },
      },
      {
        id: "l02-e-features-resampler",
        from: "l02-features",
        to: "l02-resampler",
        label: "K,V + mask",
      },
      {
        id: "l02-e-features-qformer",
        from: "l02-features",
        to: "l02-qformer",
        label: "K,V + mask",
        via: [{ x: 190, y: 180 }, { x: 190, y: 292 }],
        labelAt: { x: 192, y: 254 },
      },
      {
        id: "l02-e-mlp-tokens",
        from: "l02-mlp",
        to: "l02-tokens",
        label: "Tin tokens",
        via: [{ x: 420, y: 68 }, { x: 420, y: 180 }],
        labelAt: { x: 424, y: 108 },
      },
      {
        id: "l02-e-resampler-tokens",
        from: "l02-resampler",
        to: "l02-tokens",
        label: "Q latents",
      },
      {
        id: "l02-e-qformer-tokens",
        from: "l02-qformer",
        to: "l02-tokens",
        label: "Q latents",
        via: [{ x: 420, y: 292 }, { x: 420, y: 180 }],
        labelAt: { x: 424, y: 258 },
      },
      {
        id: "l02-e-tokens-thinker",
        from: "l02-tokens",
        to: "l02-thinker",
        label: "同一预算",
      },
      {
        id: "l02-e-thinker-probe",
        from: "l02-thinker",
        to: "l02-probe",
        label: "任务输出",
      },
    ],
    steps: [
      {
        title: "锁定 encoder features",
        description:
          "三臂读取同一批 feature、padding mask 和时间戳，不改变 encoder revision。",
        focus: ["l02-features"],
      },
      {
        title: "建立 MLP 基准",
        description:
          "原始 MLP 对每个有效 feature 独立投影，因此输出 token 数仍等于有效输入长度。",
        focus: [
          "l02-features",
          "l02-mlp",
          "l02-tokens",
          "l02-e-features-mlp",
          "l02-e-mlp-tokens",
        ],
      },
      {
        title: "用固定 query 压缩",
        description:
          "Resampler 以 learned queries 读取全部有效 feature，输出长度由 query 数 Q 决定。",
        focus: [
          "l02-features",
          "l02-resampler",
          "l02-tokens",
          "l02-e-features-resampler",
          "l02-e-resampler-tokens",
        ],
      },
      {
        title: "加入 query 间交互",
        description:
          "轻量 Q-Former 在 cross-attention 之外加入 query self-attention，但仍保持固定 Q 个输出。",
        focus: [
          "l02-features",
          "l02-qformer",
          "l02-tokens",
          "l02-e-features-qformer",
          "l02-e-qformer-tokens",
        ],
      },
      {
        title: "验证模型使用了模态",
        description:
          "在冻结的 Thinker 上分别输入正确、全零和 batch 内错配媒体；只有输出随媒体改变，任务分数才有模态证据。",
        focus: [
          "l02-tokens",
          "l02-thinker",
          "l02-probe",
          "l02-e-tokens-thinker",
          "l02-e-thinker-probe",
        ],
      },
    ],
    facts: [
      "逐 token MLP 做维度映射，但不会主动减少 encoder token 数。",
      "Learned-query connector 的输出长度由 query 数 Q 决定。",
      "三臂比较必须固定 encoder、Thinker、训练 token 和近似参数预算。",
      "正确媒体与错配媒体结果接近时，不能证明模型使用了该模态。",
    ],
  },
  {
    lessonId: "03",
    title: "Codec 重建与 Talker 预测的两条误差路径",
    summary:
      "同一原始波形先检查 codec 重建，再把离散 code 作为 Talker target 单独评估。",
    viewBox: "0 0 1040 360",
    nodes: [
      {
        id: "l03-wave",
        label: ["原始 waveform"],
        meta: "统一采样率",
        kind: "input",
        x: 80,
        y: 220,
      },
      {
        id: "l03-encoder",
        label: ["Codec encoder"],
        meta: "frame → RVQ",
        kind: "transform",
        x: 250,
        y: 220,
      },
      {
        id: "l03-codes",
        label: ["离散 codec codes"],
        meta: "[B, Q, T]",
        kind: "state",
        x: 430,
        y: 220,
      },
      {
        id: "l03-condition",
        label: ["Thinker 条件"],
        meta: "text / bridge hidden",
        kind: "input",
        x: 430,
        y: 72,
      },
      {
        id: "l03-talker",
        label: ["Talker"],
        meta: "预测 Q 路 code",
        kind: "transform",
        x: 650,
        y: 72,
      },
      {
        id: "l03-generated",
        label: ["生成 codes"],
        meta: "free-running",
        kind: "state",
        x: 830,
        y: 72,
      },
      {
        id: "l03-decoder",
        label: ["Codec decoder"],
        meta: "chunked / stateful",
        kind: "transform",
        x: 785,
        y: 220,
      },
      {
        id: "l03-output",
        label: ["重建或生成音频"],
        meta: "PCM",
        kind: "output",
        x: 945,
        y: 220,
        width: 142,
      },
    ],
    edges: [
      {
        id: "l03-e-wave-encoder",
        from: "l03-wave",
        to: "l03-encoder",
        label: "固定 waveform",
      },
      {
        id: "l03-e-encoder-codes",
        from: "l03-encoder",
        to: "l03-codes",
        label: "Q × T indices",
      },
      {
        id: "l03-e-codes-decoder",
        from: "l03-codes",
        to: "l03-decoder",
        label: "codec-only",
      },
      {
        id: "l03-e-condition-talker",
        from: "l03-condition",
        to: "l03-talker",
        label: "语义条件",
      },
      {
        id: "l03-e-codes-talker",
        from: "l03-codes",
        to: "l03-talker",
        label: "teacher-forced target",
        via: [{ x: 500, y: 220 }, { x: 500, y: 72 }],
        labelAt: { x: 505, y: 152 },
      },
      {
        id: "l03-e-talker-generated",
        from: "l03-talker",
        to: "l03-generated",
        label: "sampled indices",
      },
      {
        id: "l03-e-generated-decoder",
        from: "l03-generated",
        to: "l03-decoder",
        label: "同一 adapter",
      },
      {
        id: "l03-e-decoder-output",
        from: "l03-decoder",
        to: "l03-output",
        label: "PCM chunks",
      },
    ],
    steps: [
      {
        title: "只比较 codec",
        description:
          "各候选从同一原始 waveform 编码；先测码率、重建和边界，不让 Talker 误差进入结果。",
        focus: [
          "l03-wave",
          "l03-encoder",
          "l03-codes",
          "l03-e-wave-encoder",
          "l03-e-encoder-codes",
        ],
      },
      {
        title: "验证 adapter 契约",
        description:
          "每个 adapter 明确采样率、帧率、码本数、各码本词表和 [B,Q,T] 布局。",
        focus: ["l03-encoder", "l03-codes", "l03-e-encoder-codes"],
      },
      {
        title: "测 codec 重建上限",
        description:
          "目标 codes 直接进入对应 decoder，得到 codec-only reconstruction；这一步不调用 Talker。",
        focus: [
          "l03-codes",
          "l03-decoder",
          "l03-output",
          "l03-e-codes-decoder",
          "l03-e-decoder-output",
        ],
      },
      {
        title: "训练 Talker 预测同一 code",
        description:
          "Talker 读取相同 Thinker 条件，以该 codec 的离散 code 为 target；Q、vocab 和 delay 随 CodecSpec 配置。",
        focus: [
          "l03-condition",
          "l03-codes",
          "l03-talker",
          "l03-e-condition-talker",
          "l03-e-codes-talker",
        ],
      },
      {
        title: "端到端解码生成 code",
        description:
          "free-running Talker code 通过同一 decoder 变成 PCM；最终联合比较 WER、音质、TTFA 与 RTF。",
        focus: [
          "l03-talker",
          "l03-generated",
          "l03-decoder",
          "l03-output",
          "l03-e-talker-generated",
          "l03-e-generated-decoder",
          "l03-e-decoder-output",
        ],
      },
    ],
    facts: [
      "Nominal bitrate 为帧率乘以各码本 log2 词表大小之和。",
      "Codec-only reconstruction 与 Talker free-running generation 必须分开报告。",
      "替换 codec 时必须同时更新 Q、vocab、delay、stop/pad 和时间轴。",
      "流式测试需要检查 offline/streaming 等价、state reset 和 chunk 边界。",
    ],
  },
  {
    lessonId: "04",
    title: "八码本 Talker 的三种生成拓扑",
    summary:
      "三臂读取同一 canonical Mimi codes，只改变 outer schedule 和同帧条件方式。",
    viewBox: "0 0 1040 360",
    nodes: [
      {
        id: "l04-canonical",
        label: ["Canonical codes"],
        meta: "[B, 8, frames]",
        kind: "input",
        x: 88,
        y: 180,
      },
      {
        id: "l04-diagonal",
        label: ["A · Diagonal"],
        meta: "q 路右移 q 步",
        kind: "transform",
        x: 300,
        y: 68,
      },
      {
        id: "l04-parallel",
        label: ["B · Same-frame"],
        meta: "8 heads independent",
        kind: "transform",
        x: 300,
        y: 180,
      },
      {
        id: "l04-depth",
        label: ["C · Grouped depth"],
        meta: "q0:q3 → q4:q7",
        kind: "transform",
        x: 300,
        y: 292,
      },
      {
        id: "l04-logits",
        label: ["八码本 logits"],
        meta: "per-q loss / sampling",
        kind: "state",
        x: 550,
        y: 180,
      },
      {
        id: "l04-frames",
        label: ["完整 codec frames"],
        meta: "[B, ready, 8]",
        kind: "state",
        x: 760,
        y: 180,
      },
      {
        id: "l04-pcm",
        label: ["Mimi → PCM"],
        meta: "首帧与持续速率",
        kind: "output",
        x: 950,
        y: 180,
      },
    ],
    edges: [
      {
        id: "l04-e-canonical-diagonal",
        from: "l04-canonical",
        to: "l04-diagonal",
        label: "delay targets",
        via: [{ x: 190, y: 180 }, { x: 190, y: 68 }],
        labelAt: { x: 194, y: 108 },
      },
      {
        id: "l04-e-canonical-parallel",
        from: "l04-canonical",
        to: "l04-parallel",
        label: "same frame",
      },
      {
        id: "l04-e-canonical-depth",
        from: "l04-canonical",
        to: "l04-depth",
        label: "group targets",
        via: [{ x: 190, y: 180 }, { x: 190, y: 292 }],
        labelAt: { x: 194, y: 258 },
      },
      {
        id: "l04-e-diagonal-logits",
        from: "l04-diagonal",
        to: "l04-logits",
        label: "temporal history",
        via: [{ x: 425, y: 68 }, { x: 425, y: 180 }],
        labelAt: { x: 430, y: 108 },
      },
      {
        id: "l04-e-parallel-logits",
        from: "l04-parallel",
        to: "l04-logits",
        label: "同一 h_t",
      },
      {
        id: "l04-e-depth-logits",
        from: "l04-depth",
        to: "l04-logits",
        label: "sampled group 0",
        via: [{ x: 425, y: 292 }, { x: 425, y: 180 }],
        labelAt: { x: 430, y: 258 },
      },
      {
        id: "l04-e-logits-frames",
        from: "l04-logits",
        to: "l04-frames",
        label: "schedule inverse",
      },
      {
        id: "l04-e-frames-pcm",
        from: "l04-frames",
        to: "l04-pcm",
        label: "8 codes / frame",
      },
    ],
    steps: [
      {
        title: "固定 canonical codes",
        description:
          "三臂读取同一 [B,8,frames] target、相同 speaker condition 和相同有效 audio frame 数。",
        focus: ["l04-canonical"],
      },
      {
        title: "执行 diagonal delay",
        description:
          "第 q 路右移 q 个 schedule step；同一物理帧的 8 个 code 在不同 temporal step 产生。",
        focus: [
          "l04-canonical",
          "l04-diagonal",
          "l04-logits",
          "l04-e-canonical-diagonal",
          "l04-e-diagonal-logits",
        ],
      },
      {
        title: "同帧独立预测",
        description:
          "8 个 head 都只读取同一 temporal hidden h_t，不读取本帧其他 code 的采样结果。",
        focus: [
          "l04-canonical",
          "l04-parallel",
          "l04-logits",
          "l04-e-canonical-parallel",
          "l04-e-parallel-logits",
        ],
      },
      {
        title: "加入分组 depth 条件",
        description:
          "先采样 q0:q3，再让 q4:q7 的 depth block 读取该组 embedding；因此帧内串行深度为 2。",
        focus: [
          "l04-canonical",
          "l04-depth",
          "l04-logits",
          "l04-e-canonical-depth",
          "l04-e-depth-logits",
        ],
      },
      {
        title: "按完整帧测量系统结果",
        description:
          "所有拓扑都先还原为完整八码本 frame，再用同一 Mimi 解码并测 WER、TTFA、RTF 与听感。",
        focus: [
          "l04-logits",
          "l04-frames",
          "l04-pcm",
          "l04-e-logits-frames",
          "l04-e-frames-pcm",
        ],
      },
    ],
    facts: [
      "Diagonal schedule shift 与 causal next-token shift 是两次不同的索引变换。",
      "Same-frame parallel 没有 q0→q7 条件；grouped depth 显式加入一层帧内依赖。",
      "Teacher-forced per-q PPL 不能替代 free-running 音频和听感评测。",
      "TTFA 从请求开始计到首个可播放 PCM，而不是首个 q0 logit。",
    ],
  },
  {
    lessonId: "05",
    title: "因果 Listener 的可用时间链",
    summary:
      "每个音频 packet 只产生已经到达的 feature，并把 source span 与 available_at 一起交给 Thinker。",
    viewBox: "0 0 960 360",
    nodes: [
      {
        id: "l05-packets",
        label: ["16 kHz PCM packets"],
        meta: "arrival time",
        kind: "input",
        x: 85,
        y: 150,
      },
      {
        id: "l05-frontend",
        label: ["Streaming frontend"],
        meta: "fbank / subsample",
        kind: "transform",
        x: 270,
        y: 150,
      },
      {
        id: "l05-student",
        label: ["Causal student"],
        meta: "stateful encoder",
        kind: "transform",
        x: 465,
        y: 150,
      },
      {
        id: "l05-clock",
        label: ["Feature timestamps"],
        meta: "source span / available_at",
        kind: "state",
        x: 270,
        y: 292,
        width: 166,
      },
      {
        id: "l05-kv",
        label: ["Thinker prefix KV"],
        meta: "append after available_at",
        kind: "state",
        x: 665,
        y: 150,
      },
      {
        id: "l05-endpoint",
        label: ["Endpoint head"],
        meta: "CONTINUE / END",
        kind: "decision",
        x: 560,
        y: 292,
        width: 158,
      },
      {
        id: "l05-response",
        label: ["Assistant generation"],
        meta: "reuse prefix KV",
        kind: "output",
        x: 875,
        y: 150,
        width: 158,
      },
    ],
    edges: [
      {
        id: "l05-e-packets-frontend",
        from: "l05-packets",
        to: "l05-frontend",
        label: "new samples only",
      },
      {
        id: "l05-e-frontend-student",
        from: "l05-frontend",
        to: "l05-student",
        label: "causal frames",
      },
      {
        id: "l05-e-frontend-clock",
        from: "l05-frontend",
        to: "l05-clock",
        label: "source_start / end",
      },
      {
        id: "l05-e-clock-kv",
        from: "l05-clock",
        to: "l05-kv",
        label: "time gate",
        via: [{ x: 400, y: 292 }, { x: 400, y: 228 }, { x: 665, y: 228 }],
        labelAt: { x: 505, y: 248 },
      },
      {
        id: "l05-e-student-kv",
        from: "l05-student",
        to: "l05-kv",
        label: "new embeddings",
      },
      {
        id: "l05-e-student-endpoint",
        from: "l05-student",
        to: "l05-endpoint",
        label: "acoustic state",
      },
      {
        id: "l05-e-kv-response",
        from: "l05-kv",
        to: "l05-response",
        label: "assistant header",
      },
      {
        id: "l05-e-endpoint-response",
        from: "l05-endpoint",
        to: "l05-response",
        label: "UTTERANCE_END",
        via: [{ x: 700, y: 292 }, { x: 790, y: 292 }, { x: 790, y: 150 }],
        labelAt: { x: 744, y: 312 },
      },
    ],
    steps: [
      {
        title: "按到达顺序接收 packet",
        description:
          "Listener 只接收当前已经到达的 PCM；离线完整 waveform 不能预先放进主实验缓存。",
        focus: ["l05-packets", "l05-frontend", "l05-e-packets-frontend"],
      },
      {
        title: "维护有状态 causal encoder",
        description:
          "frontend 和 student 只保存过去的卷积、attention 或 memory state，不重算未来 suffix。",
        focus: [
          "l05-frontend",
          "l05-student",
          "l05-e-frontend-student",
        ],
      },
      {
        title: "记录 feature 可用时间",
        description:
          "每个 feature 绑定 source_start、source_end 和 available_at；lookahead 与计算时间都要计入。",
        focus: [
          "l05-frontend",
          "l05-clock",
          "l05-e-frontend-clock",
        ],
      },
      {
        title: "增量推进 Thinker KV",
        description:
          "只有 clock 到达 available_at 后，新 embedding 才能追加到 Thinker prefix KV。",
        focus: [
          "l05-clock",
          "l05-student",
          "l05-kv",
          "l05-e-clock-kv",
          "l05-e-student-kv",
        ],
      },
      {
        title: "结束话轮后复用前缀",
        description:
          "Endpoint 发出 UTTERANCE_END 后直接在现有 KV 上追加 assistant header，不重新编码整段用户语音。",
        focus: [
          "l05-kv",
          "l05-endpoint",
          "l05-response",
          "l05-e-student-endpoint",
          "l05-e-kv-response",
          "l05-e-endpoint-response",
        ],
      },
    ],
    facts: [
      "Chunked 输入只有在 encoder 不读取未来且状态可复用时才属于因果 streaming。",
      "available_at 至少等于 source_end、lookahead 和编码耗时之和。",
      "修改未来 suffix 不得改变共享前缀已经发布的 feature、endpoint logit 或 Thinker state。",
      "SenseVoice teacher 的离线 hidden 只能用于蒸馏或 upper bound。",
    ],
  },
  {
    lessonId: "06",
    title: "Turn Policy 从时序特征到事件评分",
    summary:
      "四动作概率先校准并经过 hysteresis，再与同一 session 的参考事件做一对一匹配。",
    viewBox: "0 0 1040 360",
    nodes: [
      {
        id: "l06-session",
        label: ["双声道 session"],
        meta: "user / assistant",
        kind: "input",
        x: 80,
        y: 155,
      },
      {
        id: "l06-features",
        label: ["因果特征"],
        meta: "每 80 ms",
        kind: "state",
        x: 245,
        y: 155,
      },
      {
        id: "l06-head",
        label: ["TurnHead"],
        meta: "4 action logits",
        kind: "transform",
        x: 420,
        y: 155,
      },
      {
        id: "l06-calibration",
        label: ["概率校准"],
        meta: "dev temperature",
        kind: "transform",
        x: 590,
        y: 155,
      },
      {
        id: "l06-hysteresis",
        label: ["Hysteresis"],
        meta: "threshold / K / cooldown",
        kind: "decision",
        x: 760,
        y: 155,
        width: 158,
      },
      {
        id: "l06-actions",
        label: ["话轮动作事件"],
        meta: "HOLD / TAKE / BACK / BARGE",
        kind: "output",
        x: 950,
        y: 155,
        width: 154,
      },
      {
        id: "l06-reference",
        label: ["参考事件窗口"],
        meta: "preferred / acceptable",
        kind: "input",
        x: 245,
        y: 300,
        width: 160,
      },
      {
        id: "l06-evaluator",
        label: ["Session evaluator"],
        meta: "one-to-one matching",
        kind: "output",
        x: 590,
        y: 300,
        width: 166,
      },
    ],
    edges: [
      {
        id: "l06-e-session-features",
        from: "l06-session",
        to: "l06-features",
        label: "activity + context",
      },
      {
        id: "l06-e-features-head",
        from: "l06-features",
        to: "l06-head",
        label: "causal state",
      },
      {
        id: "l06-e-head-calibration",
        from: "l06-head",
        to: "l06-calibration",
        label: "raw probability",
      },
      {
        id: "l06-e-calibration-hysteresis",
        from: "l06-calibration",
        to: "l06-hysteresis",
        label: "calibrated P(action)",
      },
      {
        id: "l06-e-hysteresis-actions",
        from: "l06-hysteresis",
        to: "l06-actions",
        label: "event at time t",
      },
      {
        id: "l06-e-reference-evaluator",
        from: "l06-reference",
        to: "l06-evaluator",
        label: "anchor + tolerance",
      },
      {
        id: "l06-e-actions-evaluator",
        from: "l06-actions",
        to: "l06-evaluator",
        label: "predicted events",
        via: [{ x: 950, y: 300 }, { x: 685, y: 300 }],
        labelAt: { x: 820, y: 320 },
      },
    ],
    steps: [
      {
        title: "按 80 ms 形成因果特征",
        description:
          "每帧组合用户与助手 activity、对话状态和当前播放状态；主实验特征不得来自未来 waveform。",
        focus: [
          "l06-session",
          "l06-features",
          "l06-e-session-features",
        ],
      },
      {
        title: "预测四动作概率",
        description:
          "TurnHead 同时输出 HOLD、TAKE_TURN、BACKCHANNEL 和 BARGE_IN logits。",
        focus: [
          "l06-features",
          "l06-head",
          "l06-e-features-head",
        ],
      },
      {
        title: "在 dev 上校准",
        description:
          "Temperature scaling 只使用 dev；test 前固定校准参数、阈值和行为 cost。",
        focus: [
          "l06-head",
          "l06-calibration",
          "l06-e-head-calibration",
        ],
      },
      {
        title: "用 hysteresis 发出事件",
        description:
          "进入阈值、连续 K 帧和 cooldown 抑制概率抖动；运行时仍保存未经阈值处理的概率。",
        focus: [
          "l06-calibration",
          "l06-hysteresis",
          "l06-actions",
          "l06-e-calibration-hysteresis",
          "l06-e-hysteresis-actions",
        ],
      },
      {
        title: "按 session 一对一计分",
        description:
          "预测事件与参考窗口先最大化兼容匹配数，再最小化时间差；剩余项分别记为 spurious 和 missed。",
        focus: [
          "l06-actions",
          "l06-reference",
          "l06-evaluator",
          "l06-e-reference-evaluator",
          "l06-e-actions-evaluator",
        ],
      },
    ],
    facts: [
      "VAD 估计 speech activity，不直接给出 TAKE_TURN 或 BARGE_IN。",
      "主动作是 HOLD、TAKE_TURN、BACKCHANNEL 和 BARGE_IN。",
      "一个 prediction 不能同时命中两个 reference，反向也一样。",
      "HOLD 占比很高，因此 frame accuracy 只能作为辅助指标。",
    ],
  },
  {
    lessonId: "07",
    title: "真双工运行时的输入、分支与播放状态",
    summary:
      "输入在输出期间持续推进；控制器依据新语义选择 Continue、Pause 或 Replan。",
    viewBox: "0 0 1040 360",
    nodes: [
      {
        id: "l07-packets",
        label: ["Mic packets"],
        meta: "captured / available",
        kind: "input",
        x: 80,
        y: 170,
      },
      {
        id: "l07-listener",
        label: ["Causal listener"],
        meta: "320 ms blocks",
        kind: "transform",
        x: 250,
        y: 170,
      },
      {
        id: "l07-memory",
        label: ["User memory"],
        meta: "append-only + timestamps",
        kind: "state",
        x: 420,
        y: 170,
      },
      {
        id: "l07-controller",
        label: ["Control head"],
        meta: "Continue / Pause / Replan",
        kind: "decision",
        x: 590,
        y: 66,
        width: 166,
      },
      {
        id: "l07-branch",
        label: ["Response branch"],
        meta: "KV / cursor / status",
        kind: "state",
        x: 590,
        y: 205,
      },
      {
        id: "l07-decode",
        label: ["decode_step"],
        meta: "one microstep",
        kind: "transform",
        x: 770,
        y: 205,
      },
      {
        id: "l07-buffer",
        label: ["Cancelable PCM buffer"],
        meta: "generated / sent / played",
        kind: "state",
        x: 770,
        y: 316,
        width: 172,
      },
      {
        id: "l07-speaker",
        label: ["Speaker output"],
        meta: "played audio",
        kind: "output",
        x: 950,
        y: 316,
      },
    ],
    edges: [
      {
        id: "l07-e-packets-listener",
        from: "l07-packets",
        to: "l07-listener",
        label: "arrival order",
      },
      {
        id: "l07-e-listener-memory",
        from: "l07-listener",
        to: "l07-memory",
        label: "new features",
      },
      {
        id: "l07-e-memory-controller",
        from: "l07-memory",
        to: "l07-controller",
        label: "新输入语义",
        via: [{ x: 470, y: 170 }, { x: 470, y: 66 }],
        labelAt: { x: 474, y: 118 },
      },
      {
        id: "l07-e-controller-branch",
        from: "l07-controller",
        to: "l07-branch",
        label: "状态转换",
      },
      {
        id: "l07-e-memory-branch",
        from: "l07-memory",
        to: "l07-branch",
        label: "fusion 或 cross-memory",
      },
      {
        id: "l07-e-branch-decode",
        from: "l07-branch",
        to: "l07-decode",
        label: "active branch",
      },
      {
        id: "l07-e-decode-buffer",
        from: "l07-decode",
        to: "l07-buffer",
        label: "codec → PCM",
      },
      {
        id: "l07-e-controller-buffer",
        from: "l07-controller",
        to: "l07-buffer",
        label: "PAUSE / REPLAN cancel",
        via: [{ x: 650, y: 66 }, { x: 650, y: 316 }],
        labelAt: { x: 704, y: 128 },
      },
      {
        id: "l07-e-buffer-speaker",
        from: "l07-buffer",
        to: "l07-speaker",
        label: "deadline playback",
      },
    ],
    steps: [
      {
        title: "输出期间继续消费输入",
        description:
          "AudioIngress 不等待 generator 结束；每个 packet 按 available_at 和 sequence number 进入 listener。",
        focus: [
          "l07-packets",
          "l07-listener",
          "l07-memory",
          "l07-e-packets-listener",
          "l07-e-listener-memory",
        ],
      },
      {
        title: "根据新语义选择动作",
        description:
          "Control head 读取持续增长的 user memory；backchannel 可 Continue，未完成输入可 Pause，纠正或新问题触发 Replan。",
        focus: [
          "l07-memory",
          "l07-controller",
          "l07-e-memory-controller",
        ],
      },
      {
        title: "更新版本化 branch",
        description:
          "Pause 保存原 branch；Resume 恢复同一 KV。Replan 将旧 branch 标为 superseded，并建立带 parent 的新 branch。",
        focus: [
          "l07-controller",
          "l07-memory",
          "l07-branch",
          "l07-e-controller-branch",
          "l07-e-memory-branch",
        ],
      },
      {
        title: "以 microstep 推进生成",
        description:
          "调度器每次只执行一个 decode_step，随后重新处理 ingress 与 control，避免长生命周期锁。",
        focus: [
          "l07-branch",
          "l07-decode",
          "l07-e-branch-decode",
        ],
      },
      {
        title: "只撤销尚未播放的音频",
        description:
          "Pause 或 Replan 丢弃 pending PCM；已经播放的音频不可回收，旧 branch 的后续输出不得进入扬声器。",
        focus: [
          "l07-controller",
          "l07-decode",
          "l07-buffer",
          "l07-speaker",
          "l07-e-decode-buffer",
          "l07-e-controller-buffer",
          "l07-e-buffer-speaker",
        ],
      },
    ],
    facts: [
      "检测到人声后 cancel generator 仍不等于语义层面的 full duplex。",
      "所有输入必须满足 consumed_at ≥ available_at ≥ source_end。",
      "Pause/Resume 保留同一 branch；只有 Replan 建立新 branch。",
      "单 GPU microstep scheduler 可在保持状态顺序的同时处理新输入。",
    ],
  },
];
