import type { LessonDiagram } from "@/lib/lesson-diagrams/types";

export const systemDiagrams: LessonDiagram[] = [
  {
    lessonId: "08",
    title: "动态图像输入的位置契约",
    summary:
      "图像布局先决定 encoder token；resampler 再把每张图压到固定 64 个 LLM token，并保留二维 query 坐标和图像身份。",
    viewBox: "0 0 960 420",
    nodes: [
      {
        id: "l08-source",
        label: ["单图或多图"],
        meta: "原始宽高",
        kind: "input",
        x: 78,
        y: 120,
        width: 126,
      },
      {
        id: "l08-planner",
        label: ["Dynamic tile", "planner"],
        meta: "pixel budget",
        kind: "transform",
        x: 230,
        y: 120,
        width: 142,
      },
      {
        id: "l08-encoder",
        label: ["冻结 SigLIP2"],
        meta: "[tiles, P, D]",
        kind: "transform",
        x: 390,
        y: 120,
        width: 138,
      },
      {
        id: "l08-resampler",
        label: ["64-query", "resampler"],
        meta: "[64, D] / 图",
        kind: "transform",
        x: 550,
        y: 120,
        width: 142,
      },
      {
        id: "l08-position",
        label: ["位置契约"],
        meta: "image_id, y, x",
        kind: "state",
        x: 520,
        y: 302,
        width: 158,
      },
      {
        id: "l08-mode",
        label: ["位置编码"],
        meta: "08A: 1D · 08B: M-RoPE",
        kind: "decision",
        x: 700,
        y: 302,
        width: 174,
        height: 76,
      },
      {
        id: "l08-packer",
        label: ["Vision token", "packer"],
        meta: "64 placeholders / 图",
        kind: "transform",
        x: 730,
        y: 120,
        width: 148,
      },
      {
        id: "l08-thinker",
        label: ["Thinker"],
        meta: "embeds + position",
        kind: "output",
        x: 890,
        y: 120,
        width: 126,
      },
    ],
    edges: [
      {
        id: "l08-e-source-plan",
        from: "l08-source",
        to: "l08-planner",
        label: "image",
      },
      {
        id: "l08-e-plan-encoder",
        from: "l08-planner",
        to: "l08-encoder",
        label: "tiles",
      },
      {
        id: "l08-e-encoder-resampler",
        from: "l08-encoder",
        to: "l08-resampler",
        label: "patch features",
      },
      {
        id: "l08-e-resampler-packer",
        from: "l08-resampler",
        to: "l08-packer",
        label: "64 embeds",
      },
      {
        id: "l08-e-plan-position",
        from: "l08-planner",
        to: "l08-position",
        label: "layout",
        via: [
          { x: 230, y: 238 },
          { x: 430, y: 238 },
          { x: 430, y: 302 },
        ],
        labelAt: { x: 330, y: 228 },
      },
      {
        id: "l08-e-resampler-position",
        from: "l08-resampler",
        to: "l08-position",
        label: "query_xy",
      },
      {
        id: "l08-e-position-mode",
        from: "l08-position",
        to: "l08-mode",
        label: "axes",
      },
      {
        id: "l08-e-mode-packer",
        from: "l08-mode",
        to: "l08-packer",
        label: "position ids",
        via: [
          { x: 790, y: 302 },
          { x: 790, y: 220 },
          { x: 730, y: 220 },
        ],
        labelAt: { x: 824, y: 256 },
      },
      {
        id: "l08-e-packer-thinker",
        from: "l08-packer",
        to: "l08-thinker",
        label: "packed sequence",
      },
    ],
    steps: [
      {
        title: "按预算切图",
        description:
          "planner 在 max_tiles 内选择网格；global thumbnail 只在 dynamic 配置中启用。",
        focus: ["l08-source", "l08-planner", "l08-e-source-plan"],
      },
      {
        title: "编码并压到固定长度",
        description:
          "冻结 encoder 可产生不同数量的 patch feature，但 resampler 对每张图固定输出 64 个表示。",
        focus: [
          "l08-encoder",
          "l08-resampler",
          "l08-e-plan-encoder",
          "l08-e-encoder-resampler",
        ],
      },
      {
        title: "保留二维来源",
        description:
          "layout 和 query_xy 共同生成 image_id、row、column；padding 不获得有效二维位置。",
        focus: [
          "l08-position",
          "l08-e-plan-position",
          "l08-e-resampler-position",
        ],
      },
      {
        title: "隔离位置变量",
        description:
          "08A 固定 1D RoPE 比较图像前端；08B 冻结前端后只比较 1D RoPE 与 M-RoPE。",
        focus: ["l08-mode", "l08-e-position-mode", "l08-e-mode-packer"],
      },
      {
        title: "注入 Thinker",
        description:
          "packer 必须同时对齐 visual embeds、64 个 placeholders、位置和 image segment。",
        focus: [
          "l08-packer",
          "l08-thinker",
          "l08-e-resampler-packer",
          "l08-e-packer-thinker",
        ],
      },
    ],
    facts: [
      "动态图像前端改变 encoder patch 数，不改变每张图进入 LLM 的 64-token 契约。",
      "多图具有相同局部坐标时，image_id 或 segment_id 仍必须不同。",
      "打乱 resampler 输出 query_xy 检查的是 Thinker 是否使用二维位置；打乱输入 patch_xy 检查的是 resampler。",
      "训练、评测和 WebUI 必须调用同一套 processor 与 tile planner。",
    ],
  },
  {
    lessonId: "09",
    title: "原生视频与音频的共享时间轴",
    summary:
      "视频帧和音频 chunk 各自编码，但都保留源媒体时间；AV packer 以时间排序，并用 modality id 区分同一时刻的两种 token。",
    viewBox: "0 0 960 420",
    nodes: [
      {
        id: "l09-video",
        label: ["视频"],
        meta: "源时间轴",
        kind: "input",
        x: 78,
        y: 96,
        width: 120,
      },
      {
        id: "l09-audio",
        label: ["音频"],
        meta: "源时间轴",
        kind: "input",
        x: 78,
        y: 310,
        width: 120,
      },
      {
        id: "l09-sampler",
        label: ["固定抽帧"],
        meta: "16 frames",
        kind: "transform",
        x: 238,
        y: 96,
        width: 132,
      },
      {
        id: "l09-audio-encoder",
        label: ["Audio encoder"],
        meta: "chunk centres",
        kind: "transform",
        x: 238,
        y: 310,
        width: 146,
      },
      {
        id: "l09-temporal",
        label: ["时序模块"],
        meta: "16 → 8 time cells",
        kind: "transform",
        x: 430,
        y: 96,
        width: 154,
      },
      {
        id: "l09-time",
        label: ["共享时间位置"],
        meta: "time bucket + modality",
        kind: "state",
        x: 510,
        y: 310,
        width: 176,
      },
      {
        id: "l09-packer",
        label: ["AV token packer"],
        meta: "time-ordered",
        kind: "transform",
        x: 710,
        y: 190,
        width: 158,
      },
      {
        id: "l09-thinker",
        label: ["Thinker"],
        meta: "interleaved AV",
        kind: "output",
        x: 884,
        y: 190,
        width: 126,
      },
    ],
    edges: [
      {
        id: "l09-e-video-sampler",
        from: "l09-video",
        to: "l09-sampler",
        label: "decode",
      },
      {
        id: "l09-e-sampler-temporal",
        from: "l09-sampler",
        to: "l09-temporal",
        label: "frames + ms",
      },
      {
        id: "l09-e-audio-encoder",
        from: "l09-audio",
        to: "l09-audio-encoder",
        label: "chunks",
      },
      {
        id: "l09-e-temporal-time",
        from: "l09-temporal",
        to: "l09-time",
        label: "pair midpoints",
        via: [
          { x: 430, y: 220 },
          { x: 510, y: 220 },
        ],
        labelAt: { x: 470, y: 210 },
      },
      {
        id: "l09-e-audio-time",
        from: "l09-audio-encoder",
        to: "l09-time",
        label: "chunk centres",
      },
      {
        id: "l09-e-temporal-packer",
        from: "l09-temporal",
        to: "l09-packer",
        label: "video embeds",
        via: [
          { x: 560, y: 96 },
          { x: 560, y: 150 },
          { x: 630, y: 150 },
        ],
        labelAt: { x: 594, y: 138 },
      },
      {
        id: "l09-e-audio-packer",
        from: "l09-audio-encoder",
        to: "l09-packer",
        label: "audio embeds",
        via: [
          { x: 390, y: 350 },
          { x: 630, y: 350 },
          { x: 630, y: 230 },
        ],
        labelAt: { x: 510, y: 340 },
      },
      {
        id: "l09-e-time-packer",
        from: "l09-time",
        to: "l09-packer",
        label: "time ids",
      },
      {
        id: "l09-e-packer-thinker",
        from: "l09-packer",
        to: "l09-thinker",
        label: "AV sequence",
      },
    ],
    steps: [
      {
        title: "锁定抽帧",
        description:
          "主实验使用确定性 uniform sampling；sampler 不得读取 event span、答案或 evidence。",
        focus: ["l09-video", "l09-sampler", "l09-e-video-sampler"],
      },
      {
        title: "形成八个视频时间格",
        description:
          "三臂都从同一 16 帧 encoder feature 出发，并输出八个相邻帧真实时间中点。",
        focus: [
          "l09-temporal",
          "l09-e-sampler-temporal",
          "l09-e-temporal-time",
        ],
      },
      {
        title: "保留音频中心时间",
        description:
          "audio encoder 为每个 chunk 保存中心时间；它不借用视频 frame index。",
        focus: [
          "l09-audio",
          "l09-audio-encoder",
          "l09-e-audio-encoder",
          "l09-e-audio-time",
        ],
      },
      {
        title: "按真实时间打包",
        description:
          "同一 time bucket 可以同时有音频和视频 token，modality id 负责区分来源。",
        focus: [
          "l09-time",
          "l09-packer",
          "l09-e-temporal-packer",
          "l09-e-audio-packer",
          "l09-e-time-packer",
        ],
      },
      {
        title: "进入统一因果序列",
        description:
          "Thinker 接收按时间排序的 AV token；reverse、shuffle 和 mismatch 必须使用重新计算的合法标签。",
        focus: ["l09-thinker", "l09-e-packer-thinker"],
      },
    ],
    facts: [
      "A/B/C 三臂都输出 8 个时间格、每格 32 个空间 token，总计 256 个视频 token。",
      "奇数输入帧必须在 preflight 失败，正式路径不能静默补帧。",
      "event-aware sampling 只能作为单独的 oracle upper bound。",
      "reverse、shuffle 和 audio mismatch 不能继续沿用原视频答案。",
    ],
  },
  {
    lessonId: "10",
    title: "视觉 Token Reduction 的统一输出契约",
    summary:
      "三种 reducer 可以采用不同选择规则，但必须共享同一整数 budget，并输出原始位置、token mass、keep mask 和可审计 trace。",
    viewBox: "0 0 1040 420",
    nodes: [
      {
        id: "l10-input",
        label: ["视频特征"],
        meta: "z[F,P,D] + position",
        kind: "input",
        x: 80,
        y: 205,
        width: 142,
      },
      {
        id: "l10-selector",
        label: ["Reducer mode"],
        meta: "同一整数 budget",
        kind: "decision",
        x: 245,
        y: 205,
        width: 156,
        height: 78,
      },
      {
        id: "l10-uniform",
        label: ["Uniform"],
        meta: "stratified sampling",
        kind: "transform",
        x: 430,
        y: 78,
        width: 146,
      },
      {
        id: "l10-merge",
        label: ["Similarity merge"],
        meta: "local window",
        kind: "transform",
        x: 430,
        y: 205,
        width: 154,
      },
      {
        id: "l10-evs",
        label: ["EVS"],
        meta: "temporal change",
        kind: "transform",
        x: 430,
        y: 332,
        width: 146,
      },
      {
        id: "l10-contract",
        label: ["Reducer contract"],
        meta: "position + mass + trace",
        kind: "state",
        x: 650,
        y: 205,
        width: 174,
      },
      {
        id: "l10-packer",
        label: ["Dynamic packer"],
        meta: "no deleted padding",
        kind: "transform",
        x: 835,
        y: 205,
        width: 148,
      },
      {
        id: "l10-thinker",
        label: ["Thinker"],
        meta: "log(token_mass)",
        kind: "output",
        x: 990,
        y: 205,
        width: 80,
      },
    ],
    edges: [
      {
        id: "l10-e-input-selector",
        from: "l10-input",
        to: "l10-selector",
        label: "valid tokens",
      },
      {
        id: "l10-e-selector-uniform",
        from: "l10-selector",
        to: "l10-uniform",
        label: "A",
      },
      {
        id: "l10-e-selector-merge",
        from: "l10-selector",
        to: "l10-merge",
        label: "B",
      },
      {
        id: "l10-e-selector-evs",
        from: "l10-selector",
        to: "l10-evs",
        label: "C",
      },
      {
        id: "l10-e-uniform-contract",
        from: "l10-uniform",
        to: "l10-contract",
        via: [
          { x: 545, y: 78 },
          { x: 545, y: 165 },
        ],
        label: "kept ids",
        labelAt: { x: 578, y: 108 },
      },
      {
        id: "l10-e-merge-contract",
        from: "l10-merge",
        to: "l10-contract",
        label: "mass-weighted",
      },
      {
        id: "l10-e-evs-contract",
        from: "l10-evs",
        to: "l10-contract",
        via: [
          { x: 545, y: 332 },
          { x: 545, y: 245 },
        ],
        label: "change top-k",
        labelAt: { x: 583, y: 302 },
      },
      {
        id: "l10-e-contract-packer",
        from: "l10-contract",
        to: "l10-packer",
        label: "exact length",
      },
      {
        id: "l10-e-packer-thinker",
        from: "l10-packer",
        to: "l10-thinker",
        label: "packed embeds",
      },
    ],
    steps: [
      {
        title: "固定共同输入",
        description:
          "三臂读取相同 encoder features、时空位置和 valid mask；100% budget 必须严格直通。",
        focus: ["l10-input", "l10-selector", "l10-e-input-selector"],
      },
      {
        title: "执行三种压缩",
        description:
          "Uniform 分层取样；merge 只在局部窗口配对；EVS 按同位置跨帧变化分数保留 token。",
        focus: [
          "l10-uniform",
          "l10-merge",
          "l10-evs",
          "l10-e-selector-uniform",
          "l10-e-selector-merge",
          "l10-e-selector-evs",
        ],
      },
      {
        title: "统一输出字段",
        description:
          "所有方法输出精确 token 数和原始位置；merge 额外传递代表原 token 数量的 mass。",
        focus: [
          "l10-contract",
          "l10-e-uniform-contract",
          "l10-e-merge-contract",
          "l10-e-evs-contract",
        ],
      },
      {
        title: "删除无效 padding",
        description:
          "packer 按 offsets 和 lengths 形成真正的变长序列，不能把删掉的 token 以 padding 送回 LLM。",
        focus: ["l10-packer", "l10-e-contract-packer"],
      },
      {
        title: "保持合并权重",
        description:
          "Thinker 对视觉 key 加 log(token_mass)，使一个合并 token 保留其代表的原始质量。",
        focus: ["l10-thinker", "l10-e-packer-thinker"],
      },
    ],
    facts: [
      "主比较至少扫描 100%、75%、50% 和 25% 四个保留率。",
      "三臂必须逐样本得到相同整数 keep count，不能只让平均值相同。",
      "Similarity merge 不得跨越离散的 2×2×2 时空窗口。",
      "质量、视觉 token 数、prefill 延迟和峰值显存必须同时报告。",
    ],
  },
  {
    lessonId: "11",
    title: "Shared + Routed MoE 的 token 路径",
    summary:
      "每个 token 始终经过 shared expert，同时由 router 选择 top-k routed experts；combine 前必须验证权重归一化且没有 token 丢失。",
    viewBox: "0 0 1040 420",
    nodes: [
      {
        id: "l11-hidden",
        label: ["Normalized hidden"],
        meta: "[T, D]",
        kind: "input",
        x: 84,
        y: 205,
        width: 148,
      },
      {
        id: "l11-shared",
        label: ["Shared expert"],
        meta: "all tokens",
        kind: "transform",
        x: 300,
        y: 90,
        width: 148,
      },
      {
        id: "l11-router",
        label: ["Router"],
        meta: "sigmoid + top-k",
        kind: "decision",
        x: 270,
        y: 315,
        width: 146,
        height: 74,
      },
      {
        id: "l11-dispatch",
        label: ["Token dispatch"],
        meta: "dropless",
        kind: "transform",
        x: 450,
        y: 315,
        width: 148,
      },
      {
        id: "l11-experts",
        label: ["Routed experts"],
        meta: "E experts",
        kind: "transform",
        x: 620,
        y: 315,
        width: 148,
      },
      {
        id: "l11-combine",
        label: ["Weighted combine"],
        meta: "shared + routed",
        kind: "transform",
        x: 770,
        y: 205,
        width: 154,
      },
      {
        id: "l11-output",
        label: ["Residual output"],
        meta: "[T, D]",
        kind: "output",
        x: 960,
        y: 205,
        width: 92,
      },
    ],
    edges: [
      {
        id: "l11-e-hidden-shared",
        from: "l11-hidden",
        to: "l11-shared",
        label: "all",
      },
      {
        id: "l11-e-hidden-router",
        from: "l11-hidden",
        to: "l11-router",
        label: "all",
      },
      {
        id: "l11-e-router-dispatch",
        from: "l11-router",
        to: "l11-dispatch",
        label: "ids + weights",
      },
      {
        id: "l11-e-dispatch-experts",
        from: "l11-dispatch",
        to: "l11-experts",
        label: "grouped tokens",
      },
      {
        id: "l11-e-experts-combine",
        from: "l11-experts",
        to: "l11-combine",
        label: "routed output",
      },
      {
        id: "l11-e-shared-combine",
        from: "l11-shared",
        to: "l11-combine",
        label: "shared output",
        via: [
          { x: 500, y: 90 },
          { x: 500, y: 164 },
          { x: 680, y: 164 },
        ],
        labelAt: { x: 585, y: 152 },
      },
      {
        id: "l11-e-combine-output",
        from: "l11-combine",
        to: "l11-output",
        label: "residual",
      },
    ],
    steps: [
      {
        title: "复制到两条 FFN 路径",
        description:
          "同一 normalized hidden 同时进入 shared expert 和 router；shared expert 不参与稀疏选择。",
        focus: [
          "l11-hidden",
          "l11-shared",
          "l11-router",
          "l11-e-hidden-shared",
          "l11-e-hidden-router",
        ],
      },
      {
        title: "选择 top-k experts",
        description:
          "router 产生 affinity，确定 top-k expert id，并只在选中集合内归一化组合权重。",
        focus: ["l11-router", "l11-e-router-dispatch"],
      },
      {
        title: "无丢失地分发",
        description:
          "dropless dispatch 使每个 token 恰好出现 k 次；combine 后恢复原 token 顺序。",
        focus: [
          "l11-dispatch",
          "l11-experts",
          "l11-e-dispatch-experts",
        ],
      },
      {
        title: "合并 shared 与 routed 输出",
        description:
          "routed experts 按归一化权重求和，再与每个 token 都有的 shared output 相加。",
        focus: [
          "l11-combine",
          "l11-e-experts-combine",
          "l11-e-shared-combine",
        ],
      },
      {
        title: "核对输出与负载",
        description:
          "输出进入 residual；同时记录 expert load、CV、Gini、entropy、dead steps 和 route churn。",
        focus: ["l11-output", "l11-e-combine-output"],
      },
    ],
    facts: [
      "本课固定 h_shared=256、h_routed=256、E=8、top-k=2。",
      "active width 为 256 + 2×256 = 768；total width 为 256 + 8×256 = 2304。",
      "A/C 比较 active FFN 参数，B/C 比较 total FFN 参数；router 参数需单独报告。",
      "modality × expert 热图只表示相关性，固定路由和置换 expert 才是因果负对照。",
    ],
  },
  {
    lessonId: "12",
    title: "Attention / Mamba-2 Hybrid 的共同接口",
    summary:
      "两类 mixer 接收同一 hidden、位置契约和 packed boundary；层类型不同，但输出形状与 residual/FFN 接口必须一致。",
    viewBox: "0 0 1040 420",
    nodes: [
      {
        id: "l12-input",
        label: ["Packed tokens"],
        meta: "hidden + cu_seqlens",
        kind: "input",
        x: 82,
        y: 205,
        width: 154,
      },
      {
        id: "l12-position",
        label: ["Position encoder"],
        meta: "text / image / time",
        kind: "state",
        x: 254,
        y: 205,
        width: 162,
      },
      {
        id: "l12-mixer",
        label: ["Layer mixer"],
        meta: "fixed pattern",
        kind: "decision",
        x: 426,
        y: 205,
        width: 150,
        height: 76,
      },
      {
        id: "l12-attention",
        label: ["GQA Attention"],
        meta: "K/V cache",
        kind: "transform",
        x: 606,
        y: 92,
        width: 150,
      },
      {
        id: "l12-mamba",
        label: ["Mamba-2 mixer"],
        meta: "conv + SSM state",
        kind: "transform",
        x: 606,
        y: 318,
        width: 158,
      },
      {
        id: "l12-ffn",
        label: ["Residual +", "Dense SwiGLU"],
        meta: "same D",
        kind: "transform",
        x: 800,
        y: 205,
        width: 150,
      },
      {
        id: "l12-output",
        label: ["Layer output"],
        meta: "[T, D]",
        kind: "output",
        x: 960,
        y: 205,
        width: 84,
      },
    ],
    edges: [
      {
        id: "l12-e-input-position",
        from: "l12-input",
        to: "l12-position",
        label: "contract",
      },
      {
        id: "l12-e-position-mixer",
        from: "l12-position",
        to: "l12-mixer",
        label: "hidden + position",
      },
      {
        id: "l12-e-mixer-attention",
        from: "l12-mixer",
        to: "l12-attention",
        label: "A layer",
      },
      {
        id: "l12-e-mixer-mamba",
        from: "l12-mixer",
        to: "l12-mamba",
        label: "M layer",
      },
      {
        id: "l12-e-attention-ffn",
        from: "l12-attention",
        to: "l12-ffn",
        label: "same [T,D]",
      },
      {
        id: "l12-e-mamba-ffn",
        from: "l12-mamba",
        to: "l12-ffn",
        label: "same [T,D]",
      },
      {
        id: "l12-e-ffn-output",
        from: "l12-ffn",
        to: "l12-output",
        label: "residual",
      },
    ],
    steps: [
      {
        title: "生成 packed boundary",
        description:
          "packer 输出 hidden、seq_idx 和 cu_seqlens；每条样本的 position_in_sample 从 0 开始。",
        focus: ["l12-input", "l12-e-input-position"],
      },
      {
        title: "注入同一位置契约",
        description:
          "文本序号、图像 x/y、音频 time bucket、modality 和 segment 先编码为同宽 position embedding。",
        focus: ["l12-position", "l12-e-position-mixer"],
      },
      {
        title: "按固定 pattern 选 mixer",
        description:
          "Attention 层使用 K/V cache；Mamba-2 层使用 conv state 与 SSM state，不能共享同一种 cache。",
        focus: [
          "l12-mixer",
          "l12-attention",
          "l12-mamba",
          "l12-e-mixer-attention",
          "l12-e-mixer-mamba",
        ],
      },
      {
        title: "在边界重置状态",
        description:
          "Mamba state 在每个 cu_seqlens 边界清零；Attention mask 也不得让一个 packed 样本读取另一个样本。",
        focus: ["l12-attention", "l12-mamba"],
      },
      {
        title: "回到共同 block 接口",
        description:
          "两类 mixer 都返回 [T,D]，再进入相同 residual、Dense SwiGLU 和下一层。",
        focus: [
          "l12-ffn",
          "l12-output",
          "l12-e-attention-ffn",
          "l12-e-mamba-ffn",
          "l12-e-ffn-output",
        ],
      },
    ],
    facts: [
      "12A 比较锁定随机 Thinker 的三种架构；12B 才研究官方 checkpoint 迁移。",
      "packed A+B 必须与分别运行 A、B 一致，否则存在 state 或 attention 泄漏。",
      "full-sequence 与逐 token recurrent 输出必须在数值容差内一致。",
      "2K、8K、32K 的质量、prefill、decode、cache 和 HBM 要分开测量。",
    ],
  },
  {
    lessonId: "13",
    title: "八卡 DP / EP / CP 的正交语义",
    summary:
      "DP 负责样本与参数分片，EP 负责 expert ownership，CP 负责序列分片；每个轴使用独立 process group，并在全局有效 token 上恢复同一损失。",
    viewBox: "0 0 1080 420",
    nodes: [
      {
        id: "l13-batch",
        label: ["Canonical batch"],
        meta: "same sample order",
        kind: "input",
        x: 80,
        y: 205,
        width: 152,
      },
      {
        id: "l13-mesh",
        label: ["Device mesh"],
        meta: "(DP, CP, EP)",
        kind: "decision",
        x: 250,
        y: 205,
        width: 148,
        height: 76,
      },
      {
        id: "l13-dp",
        label: ["DP / FSDP2"],
        meta: "shard_axis=dp",
        kind: "transform",
        x: 440,
        y: 78,
        width: 148,
      },
      {
        id: "l13-ep",
        label: ["Expert parallel"],
        meta: "ownership + all-to-all",
        kind: "transform",
        x: 440,
        y: 205,
        width: 164,
      },
      {
        id: "l13-cp",
        label: ["Context parallel"],
        meta: "sequence shards",
        kind: "transform",
        x: 440,
        y: 332,
        width: 158,
      },
      {
        id: "l13-global",
        label: ["Global reductions"],
        meta: "loss sum/count + C,S,T",
        kind: "state",
        x: 680,
        y: 205,
        width: 184,
      },
      {
        id: "l13-compare",
        label: ["Numerical gate"],
        meta: "single-card reference",
        kind: "decision",
        x: 880,
        y: 205,
        width: 156,
        height: 76,
      },
      {
        id: "l13-output",
        label: ["Valid run"],
        meta: "then profile",
        kind: "output",
        x: 1020,
        y: 205,
        width: 68,
      },
    ],
    edges: [
      {
        id: "l13-e-batch-mesh",
        from: "l13-batch",
        to: "l13-mesh",
        label: "serialized input",
      },
      {
        id: "l13-e-mesh-dp",
        from: "l13-mesh",
        to: "l13-dp",
        label: "A / B",
      },
      {
        id: "l13-e-mesh-ep",
        from: "l13-mesh",
        to: "l13-ep",
        label: "B / C",
      },
      {
        id: "l13-e-mesh-cp",
        from: "l13-mesh",
        to: "l13-cp",
        label: "C",
      },
      {
        id: "l13-e-dp-global",
        from: "l13-dp",
        to: "l13-global",
        label: "grad sync",
        via: [
          { x: 548, y: 78 },
          { x: 548, y: 165 },
        ],
        labelAt: { x: 582, y: 108 },
      },
      {
        id: "l13-e-ep-global",
        from: "l13-ep",
        to: "l13-global",
        label: "router stats",
      },
      {
        id: "l13-e-cp-global",
        from: "l13-cp",
        to: "l13-global",
        label: "token sums",
        via: [
          { x: 548, y: 332 },
          { x: 548, y: 245 },
        ],
        labelAt: { x: 582, y: 302 },
      },
      {
        id: "l13-e-global-compare",
        from: "l13-global",
        to: "l13-compare",
        label: "logits / grads",
      },
      {
        id: "l13-e-compare-output",
        from: "l13-compare",
        to: "l13-output",
        label: "pass",
      },
    ],
    steps: [
      {
        title: "冻结单卡参考",
        description:
          "所有并行臂读取同一 serialized batch、state dict、optimizer、seed 和有效 token 预算。",
        focus: ["l13-batch", "l13-e-batch-mesh"],
      },
      {
        title: "建立三个正交轴",
        description:
          "FSDP 只沿 dp 分片；EP 表达 expert ownership；CP 表达 context partition，三者不能复用 process group。",
        focus: [
          "l13-mesh",
          "l13-dp",
          "l13-ep",
          "l13-cp",
          "l13-e-mesh-dp",
          "l13-e-mesh-ep",
          "l13-e-mesh-cp",
        ],
      },
      {
        title: "聚合全局统计量",
        description:
          "text/audio loss 汇总 loss_sum 与 valid_count；router aux 汇总每层 C、S、T 后重新计算。",
        focus: [
          "l13-global",
          "l13-e-dp-global",
          "l13-e-ep-global",
          "l13-e-cp-global",
        ],
      },
      {
        title: "先过数值 gate",
        description:
          "逐项比较 logits、loss、selected gradients、global grad norm、optimizer state 和一步更新参数。",
        focus: ["l13-compare", "l13-e-global-compare"],
      },
      {
        title: "再测系统性能",
        description:
          "只有数值 gate 通过的配置才能比较吞吐、collective、峰值 HBM、checkpoint 和恢复时间。",
        focus: ["l13-output", "l13-e-compare-output"],
      },
    ],
    facts: [
      "A=(DP8,CP1,EP1)，B=(DP2,CP1,EP4)，C=(DP1,CP2,EP4)。",
      "canonical checkpoint 只有四个 experts，正式 EP 固定为 4。",
      "mean(rank-local loss) 不等于按全局有效 token 计算的 loss。",
      "拓扑和 collective microbenchmark 决定性能解释，但不能改变主实验 mesh。",
    ],
  },
  {
    lessonId: "14",
    title: "渐进式长上下文训练的可审计链条",
    summary:
      "位置参数、来源账本、累计 token 课程和完整 checkpoint 恢复必须同时生效；最终用远距离证据删除实验判断模型是否真的使用长上下文。",
    viewBox: "0 0 1040 420",
    nodes: [
      {
        id: "l14-checkpoint",
        label: ["固定 checkpoint"],
        meta: "revision + SHA-256",
        kind: "input",
        x: 86,
        y: 92,
        width: 152,
      },
      {
        id: "l14-data",
        label: ["Semantic ledger"],
        meta: "source + evidence span",
        kind: "input",
        x: 90,
        y: 320,
        width: 164,
      },
      {
        id: "l14-position",
        label: ["Runtime position"],
        meta: "32K reference → 128K",
        kind: "transform",
        x: 280,
        y: 92,
        width: 166,
      },
      {
        id: "l14-compiler",
        label: ["Length-view compiler"],
        meta: "token identity ledger",
        kind: "transform",
        x: 280,
        y: 320,
        width: 174,
      },
      {
        id: "l14-curriculum",
        label: ["Token curriculum"],
        meta: "8K → 32K → 128K",
        kind: "state",
        x: 520,
        y: 320,
        width: 168,
      },
      {
        id: "l14-train",
        label: ["DDP + CP1"],
        meta: "cumulative token stop",
        kind: "transform",
        x: 590,
        y: 135,
        width: 154,
      },
      {
        id: "l14-eval",
        label: ["Evidence gate"],
        meta: "original / deleted",
        kind: "decision",
        x: 800,
        y: 205,
        width: 160,
        height: 78,
      },
      {
        id: "l14-report",
        label: ["Validated length"],
        meta: "ability, not capacity",
        kind: "output",
        x: 970,
        y: 205,
        width: 92,
      },
    ],
    edges: [
      {
        id: "l14-e-checkpoint-position",
        from: "l14-checkpoint",
        to: "l14-position",
        label: "config",
      },
      {
        id: "l14-e-data-compiler",
        from: "l14-data",
        to: "l14-compiler",
        label: "source offsets",
      },
      {
        id: "l14-e-position-train",
        from: "l14-position",
        to: "l14-train",
        label: "RoPE args",
      },
      {
        id: "l14-e-compiler-curriculum",
        from: "l14-compiler",
        to: "l14-curriculum",
        label: "length views",
      },
      {
        id: "l14-e-curriculum-train",
        from: "l14-curriculum",
        to: "l14-train",
        label: "280M / 560M / 800M",
      },
      {
        id: "l14-e-train-eval",
        from: "l14-train",
        to: "l14-eval",
        label: "frozen checkpoint",
      },
      {
        id: "l14-e-compiler-eval",
        from: "l14-compiler",
        to: "l14-eval",
        label: "evidence ids",
        via: [
          { x: 390, y: 372 },
          { x: 680, y: 372 },
          { x: 680, y: 245 },
        ],
        labelAt: { x: 535, y: 362 },
      },
      {
        id: "l14-e-eval-report",
        from: "l14-eval",
        to: "l14-report",
        label: "three-seed result",
      },
    ],
    steps: [
      {
        title: "锁定训练起点",
        description:
          "checkpoint revision、文件 SHA、配置容量和公开训练长度分别记录，不能相互代填。",
        focus: [
          "l14-checkpoint",
          "l14-position",
          "l14-e-checkpoint-position",
        ],
      },
      {
        title: "编译相同来源的长度视图",
        description:
          "A/B 读取相同 semantic ledger；compiler 保存 source offset、token id、evidence distance 和 split。",
        focus: [
          "l14-data",
          "l14-compiler",
          "l14-e-data-compiler",
        ],
      },
      {
        title: "按累计 token 切换长度",
        description:
          "渐进臂依次在 280M、560M、800M non-padding token 停止；resume 必须恢复 optimizer、sampler、LR 和计数。",
        focus: [
          "l14-curriculum",
          "l14-e-compiler-curriculum",
          "l14-e-curriculum-train",
        ],
      },
      {
        title: "运行同一 DDP 主路径",
        description:
          "A/B/C 都使用 DDP、CP=1 和相同总 token 预算；128K OOM 时正式结论止于 32K。",
        focus: [
          "l14-position",
          "l14-train",
          "l14-e-position-train",
        ],
      },
      {
        title: "验证远距离证据使用",
        description:
          "原始输入答对、删除必要证据后回答无法判断、原答案概率下降，三项共同构成 evidence gate。",
        focus: [
          "l14-eval",
          "l14-report",
          "l14-e-train-eval",
          "l14-e-compiler-eval",
          "l14-e-eval-report",
        ],
      },
    ],
    facts: [
      "max_position_embeddings=131072 只证明系统容量，不证明模型能使用 128K 证据。",
      "主实验的 YaRN scaling reference 是 32768；它不是官方训练长度声明。",
      "三阶段累计停止点是 280M、560M、800M non-padding tokens。",
      "短文本 replay 占训练 token 的 10%，用于量化短上下文能力回退。",
    ],
  },
];
